// Code generated by go-swagger; DO NOT EDIT.

package ingestion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1IngestionSchedulesParams creates a new GetAPIV1IngestionSchedulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1IngestionSchedulesParams() *GetAPIV1IngestionSchedulesParams {
	return &GetAPIV1IngestionSchedulesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1IngestionSchedulesParamsWithTimeout creates a new GetAPIV1IngestionSchedulesParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1IngestionSchedulesParamsWithTimeout(timeout time.Duration) *GetAPIV1IngestionSchedulesParams {
	return &GetAPIV1IngestionSchedulesParams{
		timeout: timeout,
	}
}

// NewGetAPIV1IngestionSchedulesParamsWithContext creates a new GetAPIV1IngestionSchedulesParams object
// with the ability to set a context for a request.
func NewGetAPIV1IngestionSchedulesParamsWithContext(ctx context.Context) *GetAPIV1IngestionSchedulesParams {
	return &GetAPIV1IngestionSchedulesParams{
		Context: ctx,
	}
}

// NewGetAPIV1IngestionSchedulesParamsWithHTTPClient creates a new GetAPIV1IngestionSchedulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1IngestionSchedulesParamsWithHTTPClient(client *http.Client) *GetAPIV1IngestionSchedulesParams {
	return &GetAPIV1IngestionSchedulesParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1IngestionSchedulesParams contains all the parameters to send to the API endpoint

	for the get API v1 ingestion schedules operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1IngestionSchedulesParams struct {

	/* Enabled.

	   Filter by enabled status
	*/
	Enabled *bool

	/* Limit.

	   Limit
	*/
	Limit *int64

	/* Offset.

	   Offset
	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 ingestion schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1IngestionSchedulesParams) WithDefaults() *GetAPIV1IngestionSchedulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 ingestion schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1IngestionSchedulesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) WithTimeout(timeout time.Duration) *GetAPIV1IngestionSchedulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) WithContext(ctx context.Context) *GetAPIV1IngestionSchedulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) WithHTTPClient(client *http.Client) *GetAPIV1IngestionSchedulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnabled adds the enabled to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) WithEnabled(enabled *bool) *GetAPIV1IngestionSchedulesParams {
	o.SetEnabled(enabled)
	return o
}

// SetEnabled adds the enabled to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) SetEnabled(enabled *bool) {
	o.Enabled = enabled
}

// WithLimit adds the limit to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) WithLimit(limit *int64) *GetAPIV1IngestionSchedulesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) WithOffset(offset *int64) *GetAPIV1IngestionSchedulesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get API v1 ingestion schedules params
func (o *GetAPIV1IngestionSchedulesParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1IngestionSchedulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Enabled != nil {

		// query param enabled
		var qrEnabled bool

		if o.Enabled != nil {
			qrEnabled = *o.Enabled
		}
		qEnabled := swag.FormatBool(qrEnabled)
		if qEnabled != "" {

			if err := r.SetQueryParam("enabled", qEnabled); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
