// Code generated by go-swagger; DO NOT EDIT.

package ingestion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// GetAPIV1IngestionRunsReader is a Reader for the GetAPIV1IngestionRuns structure.
type GetAPIV1IngestionRunsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1IngestionRunsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1IngestionRunsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPIV1IngestionRunsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1IngestionRunsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/ingestion/runs] GetAPIV1IngestionRuns", response, response.Code())
	}
}

// NewGetAPIV1IngestionRunsOK creates a GetAPIV1IngestionRunsOK with default headers values
func NewGetAPIV1IngestionRunsOK() *GetAPIV1IngestionRunsOK {
	return &GetAPIV1IngestionRunsOK{}
}

/*
GetAPIV1IngestionRunsOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1IngestionRunsOK struct {
	Payload *models.V1SchedulesListJobRunsResponse
}

// IsSuccess returns true when this get Api v1 ingestion runs o k response has a 2xx status code
func (o *GetAPIV1IngestionRunsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 ingestion runs o k response has a 3xx status code
func (o *GetAPIV1IngestionRunsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 ingestion runs o k response has a 4xx status code
func (o *GetAPIV1IngestionRunsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 ingestion runs o k response has a 5xx status code
func (o *GetAPIV1IngestionRunsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 ingestion runs o k response a status code equal to that given
func (o *GetAPIV1IngestionRunsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 ingestion runs o k response
func (o *GetAPIV1IngestionRunsOK) Code() int {
	return 200
}

func (o *GetAPIV1IngestionRunsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ingestion/runs][%d] getApiV1IngestionRunsOK %s", 200, payload)
}

func (o *GetAPIV1IngestionRunsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ingestion/runs][%d] getApiV1IngestionRunsOK %s", 200, payload)
}

func (o *GetAPIV1IngestionRunsOK) GetPayload() *models.V1SchedulesListJobRunsResponse {
	return o.Payload
}

func (o *GetAPIV1IngestionRunsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1SchedulesListJobRunsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1IngestionRunsUnauthorized creates a GetAPIV1IngestionRunsUnauthorized with default headers values
func NewGetAPIV1IngestionRunsUnauthorized() *GetAPIV1IngestionRunsUnauthorized {
	return &GetAPIV1IngestionRunsUnauthorized{}
}

/*
GetAPIV1IngestionRunsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1IngestionRunsUnauthorized struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get Api v1 ingestion runs unauthorized response has a 2xx status code
func (o *GetAPIV1IngestionRunsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 ingestion runs unauthorized response has a 3xx status code
func (o *GetAPIV1IngestionRunsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 ingestion runs unauthorized response has a 4xx status code
func (o *GetAPIV1IngestionRunsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 ingestion runs unauthorized response has a 5xx status code
func (o *GetAPIV1IngestionRunsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 ingestion runs unauthorized response a status code equal to that given
func (o *GetAPIV1IngestionRunsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 ingestion runs unauthorized response
func (o *GetAPIV1IngestionRunsUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1IngestionRunsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ingestion/runs][%d] getApiV1IngestionRunsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1IngestionRunsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ingestion/runs][%d] getApiV1IngestionRunsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1IngestionRunsUnauthorized) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAPIV1IngestionRunsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1IngestionRunsInternalServerError creates a GetAPIV1IngestionRunsInternalServerError with default headers values
func NewGetAPIV1IngestionRunsInternalServerError() *GetAPIV1IngestionRunsInternalServerError {
	return &GetAPIV1IngestionRunsInternalServerError{}
}

/*
GetAPIV1IngestionRunsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAPIV1IngestionRunsInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get Api v1 ingestion runs internal server error response has a 2xx status code
func (o *GetAPIV1IngestionRunsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 ingestion runs internal server error response has a 3xx status code
func (o *GetAPIV1IngestionRunsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 ingestion runs internal server error response has a 4xx status code
func (o *GetAPIV1IngestionRunsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 ingestion runs internal server error response has a 5xx status code
func (o *GetAPIV1IngestionRunsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 ingestion runs internal server error response a status code equal to that given
func (o *GetAPIV1IngestionRunsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 ingestion runs internal server error response
func (o *GetAPIV1IngestionRunsInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1IngestionRunsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ingestion/runs][%d] getApiV1IngestionRunsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1IngestionRunsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ingestion/runs][%d] getApiV1IngestionRunsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1IngestionRunsInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAPIV1IngestionRunsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
