// Code generated by go-swagger; DO NOT EDIT.

package ingestion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1IngestionRunsIDParams creates a new GetAPIV1IngestionRunsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1IngestionRunsIDParams() *GetAPIV1IngestionRunsIDParams {
	return &GetAPIV1IngestionRunsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1IngestionRunsIDParamsWithTimeout creates a new GetAPIV1IngestionRunsIDParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1IngestionRunsIDParamsWithTimeout(timeout time.Duration) *GetAPIV1IngestionRunsIDParams {
	return &GetAPIV1IngestionRunsIDParams{
		timeout: timeout,
	}
}

// NewGetAPIV1IngestionRunsIDParamsWithContext creates a new GetAPIV1IngestionRunsIDParams object
// with the ability to set a context for a request.
func NewGetAPIV1IngestionRunsIDParamsWithContext(ctx context.Context) *GetAPIV1IngestionRunsIDParams {
	return &GetAPIV1IngestionRunsIDParams{
		Context: ctx,
	}
}

// NewGetAPIV1IngestionRunsIDParamsWithHTTPClient creates a new GetAPIV1IngestionRunsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1IngestionRunsIDParamsWithHTTPClient(client *http.Client) *GetAPIV1IngestionRunsIDParams {
	return &GetAPIV1IngestionRunsIDParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1IngestionRunsIDParams contains all the parameters to send to the API endpoint

	for the get API v1 ingestion runs ID operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1IngestionRunsIDParams struct {

	/* ID.

	   Job run ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 ingestion runs ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1IngestionRunsIDParams) WithDefaults() *GetAPIV1IngestionRunsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 ingestion runs ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1IngestionRunsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 ingestion runs ID params
func (o *GetAPIV1IngestionRunsIDParams) WithTimeout(timeout time.Duration) *GetAPIV1IngestionRunsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 ingestion runs ID params
func (o *GetAPIV1IngestionRunsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 ingestion runs ID params
func (o *GetAPIV1IngestionRunsIDParams) WithContext(ctx context.Context) *GetAPIV1IngestionRunsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 ingestion runs ID params
func (o *GetAPIV1IngestionRunsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 ingestion runs ID params
func (o *GetAPIV1IngestionRunsIDParams) WithHTTPClient(client *http.Client) *GetAPIV1IngestionRunsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 ingestion runs ID params
func (o *GetAPIV1IngestionRunsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API v1 ingestion runs ID params
func (o *GetAPIV1IngestionRunsIDParams) WithID(id string) *GetAPIV1IngestionRunsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API v1 ingestion runs ID params
func (o *GetAPIV1IngestionRunsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1IngestionRunsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
