// Code generated by go-swagger; DO NOT EDIT.

package ingestion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// PostAPIV1IngestionRunsIDCancelReader is a Reader for the PostAPIV1IngestionRunsIDCancel structure.
type PostAPIV1IngestionRunsIDCancelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1IngestionRunsIDCancelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostAPIV1IngestionRunsIDCancelNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostAPIV1IngestionRunsIDCancelUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV1IngestionRunsIDCancelNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1IngestionRunsIDCancelInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/ingestion/runs/{id}/cancel] PostAPIV1IngestionRunsIDCancel", response, response.Code())
	}
}

// NewPostAPIV1IngestionRunsIDCancelNoContent creates a PostAPIV1IngestionRunsIDCancelNoContent with default headers values
func NewPostAPIV1IngestionRunsIDCancelNoContent() *PostAPIV1IngestionRunsIDCancelNoContent {
	return &PostAPIV1IngestionRunsIDCancelNoContent{}
}

/*
PostAPIV1IngestionRunsIDCancelNoContent describes a response with status code 204, with default header values.

No Content
*/
type PostAPIV1IngestionRunsIDCancelNoContent struct {
}

// IsSuccess returns true when this post Api v1 ingestion runs Id cancel no content response has a 2xx status code
func (o *PostAPIV1IngestionRunsIDCancelNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 ingestion runs Id cancel no content response has a 3xx status code
func (o *PostAPIV1IngestionRunsIDCancelNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 ingestion runs Id cancel no content response has a 4xx status code
func (o *PostAPIV1IngestionRunsIDCancelNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 ingestion runs Id cancel no content response has a 5xx status code
func (o *PostAPIV1IngestionRunsIDCancelNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 ingestion runs Id cancel no content response a status code equal to that given
func (o *PostAPIV1IngestionRunsIDCancelNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post Api v1 ingestion runs Id cancel no content response
func (o *PostAPIV1IngestionRunsIDCancelNoContent) Code() int {
	return 204
}

func (o *PostAPIV1IngestionRunsIDCancelNoContent) Error() string {
	return fmt.Sprintf("[POST /api/v1/ingestion/runs/{id}/cancel][%d] postApiV1IngestionRunsIdCancelNoContent", 204)
}

func (o *PostAPIV1IngestionRunsIDCancelNoContent) String() string {
	return fmt.Sprintf("[POST /api/v1/ingestion/runs/{id}/cancel][%d] postApiV1IngestionRunsIdCancelNoContent", 204)
}

func (o *PostAPIV1IngestionRunsIDCancelNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1IngestionRunsIDCancelUnauthorized creates a PostAPIV1IngestionRunsIDCancelUnauthorized with default headers values
func NewPostAPIV1IngestionRunsIDCancelUnauthorized() *PostAPIV1IngestionRunsIDCancelUnauthorized {
	return &PostAPIV1IngestionRunsIDCancelUnauthorized{}
}

/*
PostAPIV1IngestionRunsIDCancelUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAPIV1IngestionRunsIDCancelUnauthorized struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post Api v1 ingestion runs Id cancel unauthorized response has a 2xx status code
func (o *PostAPIV1IngestionRunsIDCancelUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 ingestion runs Id cancel unauthorized response has a 3xx status code
func (o *PostAPIV1IngestionRunsIDCancelUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 ingestion runs Id cancel unauthorized response has a 4xx status code
func (o *PostAPIV1IngestionRunsIDCancelUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 ingestion runs Id cancel unauthorized response has a 5xx status code
func (o *PostAPIV1IngestionRunsIDCancelUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 ingestion runs Id cancel unauthorized response a status code equal to that given
func (o *PostAPIV1IngestionRunsIDCancelUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 ingestion runs Id cancel unauthorized response
func (o *PostAPIV1IngestionRunsIDCancelUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1IngestionRunsIDCancelUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/runs/{id}/cancel][%d] postApiV1IngestionRunsIdCancelUnauthorized %s", 401, payload)
}

func (o *PostAPIV1IngestionRunsIDCancelUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/runs/{id}/cancel][%d] postApiV1IngestionRunsIdCancelUnauthorized %s", 401, payload)
}

func (o *PostAPIV1IngestionRunsIDCancelUnauthorized) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostAPIV1IngestionRunsIDCancelUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1IngestionRunsIDCancelNotFound creates a PostAPIV1IngestionRunsIDCancelNotFound with default headers values
func NewPostAPIV1IngestionRunsIDCancelNotFound() *PostAPIV1IngestionRunsIDCancelNotFound {
	return &PostAPIV1IngestionRunsIDCancelNotFound{}
}

/*
PostAPIV1IngestionRunsIDCancelNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostAPIV1IngestionRunsIDCancelNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post Api v1 ingestion runs Id cancel not found response has a 2xx status code
func (o *PostAPIV1IngestionRunsIDCancelNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 ingestion runs Id cancel not found response has a 3xx status code
func (o *PostAPIV1IngestionRunsIDCancelNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 ingestion runs Id cancel not found response has a 4xx status code
func (o *PostAPIV1IngestionRunsIDCancelNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 ingestion runs Id cancel not found response has a 5xx status code
func (o *PostAPIV1IngestionRunsIDCancelNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 ingestion runs Id cancel not found response a status code equal to that given
func (o *PostAPIV1IngestionRunsIDCancelNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post Api v1 ingestion runs Id cancel not found response
func (o *PostAPIV1IngestionRunsIDCancelNotFound) Code() int {
	return 404
}

func (o *PostAPIV1IngestionRunsIDCancelNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/runs/{id}/cancel][%d] postApiV1IngestionRunsIdCancelNotFound %s", 404, payload)
}

func (o *PostAPIV1IngestionRunsIDCancelNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/runs/{id}/cancel][%d] postApiV1IngestionRunsIdCancelNotFound %s", 404, payload)
}

func (o *PostAPIV1IngestionRunsIDCancelNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostAPIV1IngestionRunsIDCancelNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1IngestionRunsIDCancelInternalServerError creates a PostAPIV1IngestionRunsIDCancelInternalServerError with default headers values
func NewPostAPIV1IngestionRunsIDCancelInternalServerError() *PostAPIV1IngestionRunsIDCancelInternalServerError {
	return &PostAPIV1IngestionRunsIDCancelInternalServerError{}
}

/*
PostAPIV1IngestionRunsIDCancelInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAPIV1IngestionRunsIDCancelInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post Api v1 ingestion runs Id cancel internal server error response has a 2xx status code
func (o *PostAPIV1IngestionRunsIDCancelInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 ingestion runs Id cancel internal server error response has a 3xx status code
func (o *PostAPIV1IngestionRunsIDCancelInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 ingestion runs Id cancel internal server error response has a 4xx status code
func (o *PostAPIV1IngestionRunsIDCancelInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 ingestion runs Id cancel internal server error response has a 5xx status code
func (o *PostAPIV1IngestionRunsIDCancelInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 ingestion runs Id cancel internal server error response a status code equal to that given
func (o *PostAPIV1IngestionRunsIDCancelInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 ingestion runs Id cancel internal server error response
func (o *PostAPIV1IngestionRunsIDCancelInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1IngestionRunsIDCancelInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/runs/{id}/cancel][%d] postApiV1IngestionRunsIdCancelInternalServerError %s", 500, payload)
}

func (o *PostAPIV1IngestionRunsIDCancelInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/runs/{id}/cancel][%d] postApiV1IngestionRunsIdCancelInternalServerError %s", 500, payload)
}

func (o *PostAPIV1IngestionRunsIDCancelInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostAPIV1IngestionRunsIDCancelInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
