// Code generated by go-swagger; DO NOT EDIT.

package ingestion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// NewPostAPIV1IngestionValidateParams creates a new PostAPIV1IngestionValidateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1IngestionValidateParams() *PostAPIV1IngestionValidateParams {
	return &PostAPIV1IngestionValidateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1IngestionValidateParamsWithTimeout creates a new PostAPIV1IngestionValidateParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1IngestionValidateParamsWithTimeout(timeout time.Duration) *PostAPIV1IngestionValidateParams {
	return &PostAPIV1IngestionValidateParams{
		timeout: timeout,
	}
}

// NewPostAPIV1IngestionValidateParamsWithContext creates a new PostAPIV1IngestionValidateParams object
// with the ability to set a context for a request.
func NewPostAPIV1IngestionValidateParamsWithContext(ctx context.Context) *PostAPIV1IngestionValidateParams {
	return &PostAPIV1IngestionValidateParams{
		Context: ctx,
	}
}

// NewPostAPIV1IngestionValidateParamsWithHTTPClient creates a new PostAPIV1IngestionValidateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1IngestionValidateParamsWithHTTPClient(client *http.Client) *PostAPIV1IngestionValidateParams {
	return &PostAPIV1IngestionValidateParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1IngestionValidateParams contains all the parameters to send to the API endpoint

	for the post API v1 ingestion validate operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1IngestionValidateParams struct {

	/* Config.

	   Config to validate
	*/
	Config *models.V1SchedulesValidateConfigRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 ingestion validate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1IngestionValidateParams) WithDefaults() *PostAPIV1IngestionValidateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 ingestion validate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1IngestionValidateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 ingestion validate params
func (o *PostAPIV1IngestionValidateParams) WithTimeout(timeout time.Duration) *PostAPIV1IngestionValidateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 ingestion validate params
func (o *PostAPIV1IngestionValidateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 ingestion validate params
func (o *PostAPIV1IngestionValidateParams) WithContext(ctx context.Context) *PostAPIV1IngestionValidateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 ingestion validate params
func (o *PostAPIV1IngestionValidateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 ingestion validate params
func (o *PostAPIV1IngestionValidateParams) WithHTTPClient(client *http.Client) *PostAPIV1IngestionValidateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 ingestion validate params
func (o *PostAPIV1IngestionValidateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfig adds the config to the post API v1 ingestion validate params
func (o *PostAPIV1IngestionValidateParams) WithConfig(config *models.V1SchedulesValidateConfigRequest) *PostAPIV1IngestionValidateParams {
	o.SetConfig(config)
	return o
}

// SetConfig adds the config to the post API v1 ingestion validate params
func (o *PostAPIV1IngestionValidateParams) SetConfig(config *models.V1SchedulesValidateConfigRequest) {
	o.Config = config
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1IngestionValidateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Config != nil {
		if err := r.SetBodyParam(o.Config); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
