// Code generated by go-swagger; DO NOT EDIT.

package ingestion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// PostAPIV1IngestionSchedulesIDTriggerReader is a Reader for the PostAPIV1IngestionSchedulesIDTrigger structure.
type PostAPIV1IngestionSchedulesIDTriggerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1IngestionSchedulesIDTriggerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV1IngestionSchedulesIDTriggerCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostAPIV1IngestionSchedulesIDTriggerUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV1IngestionSchedulesIDTriggerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1IngestionSchedulesIDTriggerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/ingestion/schedules/{id}/trigger] PostAPIV1IngestionSchedulesIDTrigger", response, response.Code())
	}
}

// NewPostAPIV1IngestionSchedulesIDTriggerCreated creates a PostAPIV1IngestionSchedulesIDTriggerCreated with default headers values
func NewPostAPIV1IngestionSchedulesIDTriggerCreated() *PostAPIV1IngestionSchedulesIDTriggerCreated {
	return &PostAPIV1IngestionSchedulesIDTriggerCreated{}
}

/*
PostAPIV1IngestionSchedulesIDTriggerCreated describes a response with status code 201, with default header values.

Created
*/
type PostAPIV1IngestionSchedulesIDTriggerCreated struct {
	Payload *models.RunsJobRun
}

// IsSuccess returns true when this post Api v1 ingestion schedules Id trigger created response has a 2xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 ingestion schedules Id trigger created response has a 3xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 ingestion schedules Id trigger created response has a 4xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 ingestion schedules Id trigger created response has a 5xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 ingestion schedules Id trigger created response a status code equal to that given
func (o *PostAPIV1IngestionSchedulesIDTriggerCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post Api v1 ingestion schedules Id trigger created response
func (o *PostAPIV1IngestionSchedulesIDTriggerCreated) Code() int {
	return 201
}

func (o *PostAPIV1IngestionSchedulesIDTriggerCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/schedules/{id}/trigger][%d] postApiV1IngestionSchedulesIdTriggerCreated %s", 201, payload)
}

func (o *PostAPIV1IngestionSchedulesIDTriggerCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/schedules/{id}/trigger][%d] postApiV1IngestionSchedulesIdTriggerCreated %s", 201, payload)
}

func (o *PostAPIV1IngestionSchedulesIDTriggerCreated) GetPayload() *models.RunsJobRun {
	return o.Payload
}

func (o *PostAPIV1IngestionSchedulesIDTriggerCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RunsJobRun)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1IngestionSchedulesIDTriggerUnauthorized creates a PostAPIV1IngestionSchedulesIDTriggerUnauthorized with default headers values
func NewPostAPIV1IngestionSchedulesIDTriggerUnauthorized() *PostAPIV1IngestionSchedulesIDTriggerUnauthorized {
	return &PostAPIV1IngestionSchedulesIDTriggerUnauthorized{}
}

/*
PostAPIV1IngestionSchedulesIDTriggerUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAPIV1IngestionSchedulesIDTriggerUnauthorized struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post Api v1 ingestion schedules Id trigger unauthorized response has a 2xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 ingestion schedules Id trigger unauthorized response has a 3xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 ingestion schedules Id trigger unauthorized response has a 4xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 ingestion schedules Id trigger unauthorized response has a 5xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 ingestion schedules Id trigger unauthorized response a status code equal to that given
func (o *PostAPIV1IngestionSchedulesIDTriggerUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 ingestion schedules Id trigger unauthorized response
func (o *PostAPIV1IngestionSchedulesIDTriggerUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1IngestionSchedulesIDTriggerUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/schedules/{id}/trigger][%d] postApiV1IngestionSchedulesIdTriggerUnauthorized %s", 401, payload)
}

func (o *PostAPIV1IngestionSchedulesIDTriggerUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/schedules/{id}/trigger][%d] postApiV1IngestionSchedulesIdTriggerUnauthorized %s", 401, payload)
}

func (o *PostAPIV1IngestionSchedulesIDTriggerUnauthorized) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostAPIV1IngestionSchedulesIDTriggerUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1IngestionSchedulesIDTriggerNotFound creates a PostAPIV1IngestionSchedulesIDTriggerNotFound with default headers values
func NewPostAPIV1IngestionSchedulesIDTriggerNotFound() *PostAPIV1IngestionSchedulesIDTriggerNotFound {
	return &PostAPIV1IngestionSchedulesIDTriggerNotFound{}
}

/*
PostAPIV1IngestionSchedulesIDTriggerNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostAPIV1IngestionSchedulesIDTriggerNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post Api v1 ingestion schedules Id trigger not found response has a 2xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 ingestion schedules Id trigger not found response has a 3xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 ingestion schedules Id trigger not found response has a 4xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 ingestion schedules Id trigger not found response has a 5xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 ingestion schedules Id trigger not found response a status code equal to that given
func (o *PostAPIV1IngestionSchedulesIDTriggerNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post Api v1 ingestion schedules Id trigger not found response
func (o *PostAPIV1IngestionSchedulesIDTriggerNotFound) Code() int {
	return 404
}

func (o *PostAPIV1IngestionSchedulesIDTriggerNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/schedules/{id}/trigger][%d] postApiV1IngestionSchedulesIdTriggerNotFound %s", 404, payload)
}

func (o *PostAPIV1IngestionSchedulesIDTriggerNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/schedules/{id}/trigger][%d] postApiV1IngestionSchedulesIdTriggerNotFound %s", 404, payload)
}

func (o *PostAPIV1IngestionSchedulesIDTriggerNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostAPIV1IngestionSchedulesIDTriggerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1IngestionSchedulesIDTriggerInternalServerError creates a PostAPIV1IngestionSchedulesIDTriggerInternalServerError with default headers values
func NewPostAPIV1IngestionSchedulesIDTriggerInternalServerError() *PostAPIV1IngestionSchedulesIDTriggerInternalServerError {
	return &PostAPIV1IngestionSchedulesIDTriggerInternalServerError{}
}

/*
PostAPIV1IngestionSchedulesIDTriggerInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAPIV1IngestionSchedulesIDTriggerInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post Api v1 ingestion schedules Id trigger internal server error response has a 2xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 ingestion schedules Id trigger internal server error response has a 3xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 ingestion schedules Id trigger internal server error response has a 4xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 ingestion schedules Id trigger internal server error response has a 5xx status code
func (o *PostAPIV1IngestionSchedulesIDTriggerInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 ingestion schedules Id trigger internal server error response a status code equal to that given
func (o *PostAPIV1IngestionSchedulesIDTriggerInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 ingestion schedules Id trigger internal server error response
func (o *PostAPIV1IngestionSchedulesIDTriggerInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1IngestionSchedulesIDTriggerInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/schedules/{id}/trigger][%d] postApiV1IngestionSchedulesIdTriggerInternalServerError %s", 500, payload)
}

func (o *PostAPIV1IngestionSchedulesIDTriggerInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/ingestion/schedules/{id}/trigger][%d] postApiV1IngestionSchedulesIdTriggerInternalServerError %s", 500, payload)
}

func (o *PostAPIV1IngestionSchedulesIDTriggerInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostAPIV1IngestionSchedulesIDTriggerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
