// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthProvidersParams creates a new GetAuthProvidersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthProvidersParams() *GetAuthProvidersParams {
	return &GetAuthProvidersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthProvidersParamsWithTimeout creates a new GetAuthProvidersParams object
// with the ability to set a timeout on a request.
func NewGetAuthProvidersParamsWithTimeout(timeout time.Duration) *GetAuthProvidersParams {
	return &GetAuthProvidersParams{
		timeout: timeout,
	}
}

// NewGetAuthProvidersParamsWithContext creates a new GetAuthProvidersParams object
// with the ability to set a context for a request.
func NewGetAuthProvidersParamsWithContext(ctx context.Context) *GetAuthProvidersParams {
	return &GetAuthProvidersParams{
		Context: ctx,
	}
}

// NewGetAuthProvidersParamsWithHTTPClient creates a new GetAuthProvidersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthProvidersParamsWithHTTPClient(client *http.Client) *GetAuthProvidersParams {
	return &GetAuthProvidersParams{
		HTTPClient: client,
	}
}

/*
GetAuthProvidersParams contains all the parameters to send to the API endpoint

	for the get auth providers operation.

	Typically these are written to a http.Request.
*/
type GetAuthProvidersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get auth providers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthProvidersParams) WithDefaults() *GetAuthProvidersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get auth providers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthProvidersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get auth providers params
func (o *GetAuthProvidersParams) WithTimeout(timeout time.Duration) *GetAuthProvidersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth providers params
func (o *GetAuthProvidersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth providers params
func (o *GetAuthProvidersParams) WithContext(ctx context.Context) *GetAuthProvidersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth providers params
func (o *GetAuthProvidersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth providers params
func (o *GetAuthProvidersParams) WithHTTPClient(client *http.Client) *GetAuthProvidersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth providers params
func (o *GetAuthProvidersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthProvidersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
