// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthProviderLoginParams creates a new GetAuthProviderLoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthProviderLoginParams() *GetAuthProviderLoginParams {
	return &GetAuthProviderLoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthProviderLoginParamsWithTimeout creates a new GetAuthProviderLoginParams object
// with the ability to set a timeout on a request.
func NewGetAuthProviderLoginParamsWithTimeout(timeout time.Duration) *GetAuthProviderLoginParams {
	return &GetAuthProviderLoginParams{
		timeout: timeout,
	}
}

// NewGetAuthProviderLoginParamsWithContext creates a new GetAuthProviderLoginParams object
// with the ability to set a context for a request.
func NewGetAuthProviderLoginParamsWithContext(ctx context.Context) *GetAuthProviderLoginParams {
	return &GetAuthProviderLoginParams{
		Context: ctx,
	}
}

// NewGetAuthProviderLoginParamsWithHTTPClient creates a new GetAuthProviderLoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthProviderLoginParamsWithHTTPClient(client *http.Client) *GetAuthProviderLoginParams {
	return &GetAuthProviderLoginParams{
		HTTPClient: client,
	}
}

/*
GetAuthProviderLoginParams contains all the parameters to send to the API endpoint

	for the get auth provider login operation.

	Typically these are written to a http.Request.
*/
type GetAuthProviderLoginParams struct {

	/* Provider.

	   OAuth provider (okta, google, github, etc.)
	*/
	Provider string

	/* RedirectURI.

	   Custom redirect URI for CLI login
	*/
	RedirectURI *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get auth provider login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthProviderLoginParams) WithDefaults() *GetAuthProviderLoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get auth provider login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthProviderLoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get auth provider login params
func (o *GetAuthProviderLoginParams) WithTimeout(timeout time.Duration) *GetAuthProviderLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth provider login params
func (o *GetAuthProviderLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth provider login params
func (o *GetAuthProviderLoginParams) WithContext(ctx context.Context) *GetAuthProviderLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth provider login params
func (o *GetAuthProviderLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth provider login params
func (o *GetAuthProviderLoginParams) WithHTTPClient(client *http.Client) *GetAuthProviderLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth provider login params
func (o *GetAuthProviderLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProvider adds the provider to the get auth provider login params
func (o *GetAuthProviderLoginParams) WithProvider(provider string) *GetAuthProviderLoginParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the get auth provider login params
func (o *GetAuthProviderLoginParams) SetProvider(provider string) {
	o.Provider = provider
}

// WithRedirectURI adds the redirectURI to the get auth provider login params
func (o *GetAuthProviderLoginParams) WithRedirectURI(redirectURI *string) *GetAuthProviderLoginParams {
	o.SetRedirectURI(redirectURI)
	return o
}

// SetRedirectURI adds the redirectUri to the get auth provider login params
func (o *GetAuthProviderLoginParams) SetRedirectURI(redirectURI *string) {
	o.RedirectURI = redirectURI
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthProviderLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	if o.RedirectURI != nil {

		// query param redirect_uri
		var qrRedirectURI string

		if o.RedirectURI != nil {
			qrRedirectURI = *o.RedirectURI
		}
		qRedirectURI := qrRedirectURI
		if qRedirectURI != "" {

			if err := r.SetQueryParam("redirect_uri", qRedirectURI); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
