// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// GetAuthProviderCallbackReader is a Reader for the GetAuthProviderCallback structure.
type GetAuthProviderCallbackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthProviderCallbackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 307:
		result := NewGetAuthProviderCallbackTemporaryRedirect()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewGetAuthProviderCallbackBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAuthProviderCallbackNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAuthProviderCallbackInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /auth/{provider}/callback] GetAuthProviderCallback", response, response.Code())
	}
}

// NewGetAuthProviderCallbackTemporaryRedirect creates a GetAuthProviderCallbackTemporaryRedirect with default headers values
func NewGetAuthProviderCallbackTemporaryRedirect() *GetAuthProviderCallbackTemporaryRedirect {
	return &GetAuthProviderCallbackTemporaryRedirect{}
}

/*
GetAuthProviderCallbackTemporaryRedirect describes a response with status code 307, with default header values.

Temporary Redirect
*/
type GetAuthProviderCallbackTemporaryRedirect struct {
	Payload string
}

// IsSuccess returns true when this get auth provider callback temporary redirect response has a 2xx status code
func (o *GetAuthProviderCallbackTemporaryRedirect) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get auth provider callback temporary redirect response has a 3xx status code
func (o *GetAuthProviderCallbackTemporaryRedirect) IsRedirect() bool {
	return true
}

// IsClientError returns true when this get auth provider callback temporary redirect response has a 4xx status code
func (o *GetAuthProviderCallbackTemporaryRedirect) IsClientError() bool {
	return false
}

// IsServerError returns true when this get auth provider callback temporary redirect response has a 5xx status code
func (o *GetAuthProviderCallbackTemporaryRedirect) IsServerError() bool {
	return false
}

// IsCode returns true when this get auth provider callback temporary redirect response a status code equal to that given
func (o *GetAuthProviderCallbackTemporaryRedirect) IsCode(code int) bool {
	return code == 307
}

// Code gets the status code for the get auth provider callback temporary redirect response
func (o *GetAuthProviderCallbackTemporaryRedirect) Code() int {
	return 307
}

func (o *GetAuthProviderCallbackTemporaryRedirect) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/{provider}/callback][%d] getAuthProviderCallbackTemporaryRedirect %s", 307, payload)
}

func (o *GetAuthProviderCallbackTemporaryRedirect) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/{provider}/callback][%d] getAuthProviderCallbackTemporaryRedirect %s", 307, payload)
}

func (o *GetAuthProviderCallbackTemporaryRedirect) GetPayload() string {
	return o.Payload
}

func (o *GetAuthProviderCallbackTemporaryRedirect) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuthProviderCallbackBadRequest creates a GetAuthProviderCallbackBadRequest with default headers values
func NewGetAuthProviderCallbackBadRequest() *GetAuthProviderCallbackBadRequest {
	return &GetAuthProviderCallbackBadRequest{}
}

/*
GetAuthProviderCallbackBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAuthProviderCallbackBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get auth provider callback bad request response has a 2xx status code
func (o *GetAuthProviderCallbackBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get auth provider callback bad request response has a 3xx status code
func (o *GetAuthProviderCallbackBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get auth provider callback bad request response has a 4xx status code
func (o *GetAuthProviderCallbackBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get auth provider callback bad request response has a 5xx status code
func (o *GetAuthProviderCallbackBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get auth provider callback bad request response a status code equal to that given
func (o *GetAuthProviderCallbackBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get auth provider callback bad request response
func (o *GetAuthProviderCallbackBadRequest) Code() int {
	return 400
}

func (o *GetAuthProviderCallbackBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/{provider}/callback][%d] getAuthProviderCallbackBadRequest %s", 400, payload)
}

func (o *GetAuthProviderCallbackBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/{provider}/callback][%d] getAuthProviderCallbackBadRequest %s", 400, payload)
}

func (o *GetAuthProviderCallbackBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAuthProviderCallbackBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuthProviderCallbackNotFound creates a GetAuthProviderCallbackNotFound with default headers values
func NewGetAuthProviderCallbackNotFound() *GetAuthProviderCallbackNotFound {
	return &GetAuthProviderCallbackNotFound{}
}

/*
GetAuthProviderCallbackNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAuthProviderCallbackNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get auth provider callback not found response has a 2xx status code
func (o *GetAuthProviderCallbackNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get auth provider callback not found response has a 3xx status code
func (o *GetAuthProviderCallbackNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get auth provider callback not found response has a 4xx status code
func (o *GetAuthProviderCallbackNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get auth provider callback not found response has a 5xx status code
func (o *GetAuthProviderCallbackNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get auth provider callback not found response a status code equal to that given
func (o *GetAuthProviderCallbackNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get auth provider callback not found response
func (o *GetAuthProviderCallbackNotFound) Code() int {
	return 404
}

func (o *GetAuthProviderCallbackNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/{provider}/callback][%d] getAuthProviderCallbackNotFound %s", 404, payload)
}

func (o *GetAuthProviderCallbackNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/{provider}/callback][%d] getAuthProviderCallbackNotFound %s", 404, payload)
}

func (o *GetAuthProviderCallbackNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAuthProviderCallbackNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuthProviderCallbackInternalServerError creates a GetAuthProviderCallbackInternalServerError with default headers values
func NewGetAuthProviderCallbackInternalServerError() *GetAuthProviderCallbackInternalServerError {
	return &GetAuthProviderCallbackInternalServerError{}
}

/*
GetAuthProviderCallbackInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAuthProviderCallbackInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get auth provider callback internal server error response has a 2xx status code
func (o *GetAuthProviderCallbackInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get auth provider callback internal server error response has a 3xx status code
func (o *GetAuthProviderCallbackInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get auth provider callback internal server error response has a 4xx status code
func (o *GetAuthProviderCallbackInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get auth provider callback internal server error response has a 5xx status code
func (o *GetAuthProviderCallbackInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get auth provider callback internal server error response a status code equal to that given
func (o *GetAuthProviderCallbackInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get auth provider callback internal server error response
func (o *GetAuthProviderCallbackInternalServerError) Code() int {
	return 500
}

func (o *GetAuthProviderCallbackInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/{provider}/callback][%d] getAuthProviderCallbackInternalServerError %s", 500, payload)
}

func (o *GetAuthProviderCallbackInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/{provider}/callback][%d] getAuthProviderCallbackInternalServerError %s", 500, payload)
}

func (o *GetAuthProviderCallbackInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAuthProviderCallbackInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
