// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// GetAPIV1MetricsAssetsByTypeReader is a Reader for the GetAPIV1MetricsAssetsByType structure.
type GetAPIV1MetricsAssetsByTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1MetricsAssetsByTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1MetricsAssetsByTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/metrics/assets/by-type] GetAPIV1MetricsAssetsByType", response, response.Code())
	}
}

// NewGetAPIV1MetricsAssetsByTypeOK creates a GetAPIV1MetricsAssetsByTypeOK with default headers values
func NewGetAPIV1MetricsAssetsByTypeOK() *GetAPIV1MetricsAssetsByTypeOK {
	return &GetAPIV1MetricsAssetsByTypeOK{}
}

/*
GetAPIV1MetricsAssetsByTypeOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1MetricsAssetsByTypeOK struct {
	Payload *models.V1MetricsAssetsByTypeResponse
}

// IsSuccess returns true when this get Api v1 metrics assets by type o k response has a 2xx status code
func (o *GetAPIV1MetricsAssetsByTypeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 metrics assets by type o k response has a 3xx status code
func (o *GetAPIV1MetricsAssetsByTypeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 metrics assets by type o k response has a 4xx status code
func (o *GetAPIV1MetricsAssetsByTypeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 metrics assets by type o k response has a 5xx status code
func (o *GetAPIV1MetricsAssetsByTypeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 metrics assets by type o k response a status code equal to that given
func (o *GetAPIV1MetricsAssetsByTypeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 metrics assets by type o k response
func (o *GetAPIV1MetricsAssetsByTypeOK) Code() int {
	return 200
}

func (o *GetAPIV1MetricsAssetsByTypeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/metrics/assets/by-type][%d] getApiV1MetricsAssetsByTypeOK %s", 200, payload)
}

func (o *GetAPIV1MetricsAssetsByTypeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/metrics/assets/by-type][%d] getApiV1MetricsAssetsByTypeOK %s", 200, payload)
}

func (o *GetAPIV1MetricsAssetsByTypeOK) GetPayload() *models.V1MetricsAssetsByTypeResponse {
	return o.Payload
}

func (o *GetAPIV1MetricsAssetsByTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1MetricsAssetsByTypeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
