// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1MetricsTopQueriesParams creates a new GetAPIV1MetricsTopQueriesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1MetricsTopQueriesParams() *GetAPIV1MetricsTopQueriesParams {
	return &GetAPIV1MetricsTopQueriesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1MetricsTopQueriesParamsWithTimeout creates a new GetAPIV1MetricsTopQueriesParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1MetricsTopQueriesParamsWithTimeout(timeout time.Duration) *GetAPIV1MetricsTopQueriesParams {
	return &GetAPIV1MetricsTopQueriesParams{
		timeout: timeout,
	}
}

// NewGetAPIV1MetricsTopQueriesParamsWithContext creates a new GetAPIV1MetricsTopQueriesParams object
// with the ability to set a context for a request.
func NewGetAPIV1MetricsTopQueriesParamsWithContext(ctx context.Context) *GetAPIV1MetricsTopQueriesParams {
	return &GetAPIV1MetricsTopQueriesParams{
		Context: ctx,
	}
}

// NewGetAPIV1MetricsTopQueriesParamsWithHTTPClient creates a new GetAPIV1MetricsTopQueriesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1MetricsTopQueriesParamsWithHTTPClient(client *http.Client) *GetAPIV1MetricsTopQueriesParams {
	return &GetAPIV1MetricsTopQueriesParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1MetricsTopQueriesParams contains all the parameters to send to the API endpoint

	for the get API v1 metrics top queries operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1MetricsTopQueriesParams struct {

	/* End.

	   End time (ISO 8601)
	*/
	End string

	/* Limit.

	   Number of results

	   Default: 10
	*/
	Limit *int64

	/* Start.

	   Start time (ISO 8601)
	*/
	Start string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 metrics top queries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1MetricsTopQueriesParams) WithDefaults() *GetAPIV1MetricsTopQueriesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 metrics top queries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1MetricsTopQueriesParams) SetDefaults() {
	var (
		limitDefault = int64(10)
	)

	val := GetAPIV1MetricsTopQueriesParams{
		Limit: &limitDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) WithTimeout(timeout time.Duration) *GetAPIV1MetricsTopQueriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) WithContext(ctx context.Context) *GetAPIV1MetricsTopQueriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) WithHTTPClient(client *http.Client) *GetAPIV1MetricsTopQueriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnd adds the end to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) WithEnd(end string) *GetAPIV1MetricsTopQueriesParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) SetEnd(end string) {
	o.End = end
}

// WithLimit adds the limit to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) WithLimit(limit *int64) *GetAPIV1MetricsTopQueriesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithStart adds the start to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) WithStart(start string) *GetAPIV1MetricsTopQueriesParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get API v1 metrics top queries params
func (o *GetAPIV1MetricsTopQueriesParams) SetStart(start string) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1MetricsTopQueriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param end
	qrEnd := o.End
	qEnd := qrEnd
	if qEnd != "" {

		if err := r.SetQueryParam("end", qEnd); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// query param start
	qrStart := o.Start
	qStart := qrStart
	if qStart != "" {

		if err := r.SetQueryParam("start", qStart); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
