// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new metrics API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new metrics API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new metrics API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for metrics API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetAPIV1Metrics(params *GetAPIV1MetricsParams, opts ...ClientOption) (*GetAPIV1MetricsOK, error)

	GetAPIV1MetricsAssetsByOwner(params *GetAPIV1MetricsAssetsByOwnerParams, opts ...ClientOption) (*GetAPIV1MetricsAssetsByOwnerOK, error)

	GetAPIV1MetricsAssetsByProvider(params *GetAPIV1MetricsAssetsByProviderParams, opts ...ClientOption) (*GetAPIV1MetricsAssetsByProviderOK, error)

	GetAPIV1MetricsAssetsByType(params *GetAPIV1MetricsAssetsByTypeParams, opts ...ClientOption) (*GetAPIV1MetricsAssetsByTypeOK, error)

	GetAPIV1MetricsAssetsTotal(params *GetAPIV1MetricsAssetsTotalParams, opts ...ClientOption) (*GetAPIV1MetricsAssetsTotalOK, error)

	GetAPIV1MetricsAssetsWithSchemas(params *GetAPIV1MetricsAssetsWithSchemasParams, opts ...ClientOption) (*GetAPIV1MetricsAssetsWithSchemasOK, error)

	GetAPIV1MetricsTopAssets(params *GetAPIV1MetricsTopAssetsParams, opts ...ClientOption) (*GetAPIV1MetricsTopAssetsOK, error)

	GetAPIV1MetricsTopQueries(params *GetAPIV1MetricsTopQueriesParams, opts ...ClientOption) (*GetAPIV1MetricsTopQueriesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetAPIV1Metrics gets metrics for UI

Get aggregated metrics for dashboard display
*/
func (a *Client) GetAPIV1Metrics(params *GetAPIV1MetricsParams, opts ...ClientOption) (*GetAPIV1MetricsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV1MetricsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1Metrics",
		Method:             "GET",
		PathPattern:        "/api/v1/metrics",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1MetricsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIV1MetricsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1Metrics: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1MetricsAssetsByOwner gets assets by owner

Get asset counts grouped by owner
*/
func (a *Client) GetAPIV1MetricsAssetsByOwner(params *GetAPIV1MetricsAssetsByOwnerParams, opts ...ClientOption) (*GetAPIV1MetricsAssetsByOwnerOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV1MetricsAssetsByOwnerParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1MetricsAssetsByOwner",
		Method:             "GET",
		PathPattern:        "/api/v1/metrics/assets/by-owner",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1MetricsAssetsByOwnerReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIV1MetricsAssetsByOwnerOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1MetricsAssetsByOwner: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1MetricsAssetsByProvider gets assets by provider

Get asset counts grouped by provider
*/
func (a *Client) GetAPIV1MetricsAssetsByProvider(params *GetAPIV1MetricsAssetsByProviderParams, opts ...ClientOption) (*GetAPIV1MetricsAssetsByProviderOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV1MetricsAssetsByProviderParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1MetricsAssetsByProvider",
		Method:             "GET",
		PathPattern:        "/api/v1/metrics/assets/by-provider",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1MetricsAssetsByProviderReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIV1MetricsAssetsByProviderOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1MetricsAssetsByProvider: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1MetricsAssetsByType gets assets by type

Get asset counts grouped by type
*/
func (a *Client) GetAPIV1MetricsAssetsByType(params *GetAPIV1MetricsAssetsByTypeParams, opts ...ClientOption) (*GetAPIV1MetricsAssetsByTypeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV1MetricsAssetsByTypeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1MetricsAssetsByType",
		Method:             "GET",
		PathPattern:        "/api/v1/metrics/assets/by-type",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1MetricsAssetsByTypeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIV1MetricsAssetsByTypeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1MetricsAssetsByType: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1MetricsAssetsTotal gets total assets count

Get the total number of assets
*/
func (a *Client) GetAPIV1MetricsAssetsTotal(params *GetAPIV1MetricsAssetsTotalParams, opts ...ClientOption) (*GetAPIV1MetricsAssetsTotalOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV1MetricsAssetsTotalParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1MetricsAssetsTotal",
		Method:             "GET",
		PathPattern:        "/api/v1/metrics/assets/total",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1MetricsAssetsTotalReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIV1MetricsAssetsTotalOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1MetricsAssetsTotal: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1MetricsAssetsWithSchemas gets assets with schemas count

Get the count of assets that have schemas defined
*/
func (a *Client) GetAPIV1MetricsAssetsWithSchemas(params *GetAPIV1MetricsAssetsWithSchemasParams, opts ...ClientOption) (*GetAPIV1MetricsAssetsWithSchemasOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV1MetricsAssetsWithSchemasParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1MetricsAssetsWithSchemas",
		Method:             "GET",
		PathPattern:        "/api/v1/metrics/assets/with-schemas",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1MetricsAssetsWithSchemasReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIV1MetricsAssetsWithSchemasOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1MetricsAssetsWithSchemas: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1MetricsTopAssets gets top viewed assets

Get the most viewed assets
*/
func (a *Client) GetAPIV1MetricsTopAssets(params *GetAPIV1MetricsTopAssetsParams, opts ...ClientOption) (*GetAPIV1MetricsTopAssetsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV1MetricsTopAssetsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1MetricsTopAssets",
		Method:             "GET",
		PathPattern:        "/api/v1/metrics/top-assets",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1MetricsTopAssetsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIV1MetricsTopAssetsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1MetricsTopAssets: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1MetricsTopQueries gets top search queries

Get the most popular search queries
*/
func (a *Client) GetAPIV1MetricsTopQueries(params *GetAPIV1MetricsTopQueriesParams, opts ...ClientOption) (*GetAPIV1MetricsTopQueriesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV1MetricsTopQueriesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1MetricsTopQueries",
		Method:             "GET",
		PathPattern:        "/api/v1/metrics/top-queries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1MetricsTopQueriesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIV1MetricsTopQueriesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1MetricsTopQueries: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
