// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRunsParams creates a new GetRunsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRunsParams() *GetRunsParams {
	return &GetRunsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRunsParamsWithTimeout creates a new GetRunsParams object
// with the ability to set a timeout on a request.
func NewGetRunsParamsWithTimeout(timeout time.Duration) *GetRunsParams {
	return &GetRunsParams{
		timeout: timeout,
	}
}

// NewGetRunsParamsWithContext creates a new GetRunsParams object
// with the ability to set a context for a request.
func NewGetRunsParamsWithContext(ctx context.Context) *GetRunsParams {
	return &GetRunsParams{
		Context: ctx,
	}
}

// NewGetRunsParamsWithHTTPClient creates a new GetRunsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRunsParamsWithHTTPClient(client *http.Client) *GetRunsParams {
	return &GetRunsParams{
		HTTPClient: client,
	}
}

/*
GetRunsParams contains all the parameters to send to the API endpoint

	for the get runs operation.

	Typically these are written to a http.Request.
*/
type GetRunsParams struct {

	/* Limit.

	   Number of results per page

	   Default: 50
	*/
	Limit *int64

	/* Offset.

	   Number of results to skip
	*/
	Offset *int64

	/* Pipelines.

	   Comma-separated list of pipeline names
	*/
	Pipelines *string

	/* Statuses.

	   Comma-separated list of statuses
	*/
	Statuses *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get runs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRunsParams) WithDefaults() *GetRunsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get runs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRunsParams) SetDefaults() {
	var (
		limitDefault = int64(50)

		offsetDefault = int64(0)
	)

	val := GetRunsParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get runs params
func (o *GetRunsParams) WithTimeout(timeout time.Duration) *GetRunsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get runs params
func (o *GetRunsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get runs params
func (o *GetRunsParams) WithContext(ctx context.Context) *GetRunsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get runs params
func (o *GetRunsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get runs params
func (o *GetRunsParams) WithHTTPClient(client *http.Client) *GetRunsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get runs params
func (o *GetRunsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get runs params
func (o *GetRunsParams) WithLimit(limit *int64) *GetRunsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get runs params
func (o *GetRunsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get runs params
func (o *GetRunsParams) WithOffset(offset *int64) *GetRunsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get runs params
func (o *GetRunsParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithPipelines adds the pipelines to the get runs params
func (o *GetRunsParams) WithPipelines(pipelines *string) *GetRunsParams {
	o.SetPipelines(pipelines)
	return o
}

// SetPipelines adds the pipelines to the get runs params
func (o *GetRunsParams) SetPipelines(pipelines *string) {
	o.Pipelines = pipelines
}

// WithStatuses adds the statuses to the get runs params
func (o *GetRunsParams) WithStatuses(statuses *string) *GetRunsParams {
	o.SetStatuses(statuses)
	return o
}

// SetStatuses adds the statuses to the get runs params
func (o *GetRunsParams) SetStatuses(statuses *string) {
	o.Statuses = statuses
}

// WriteToRequest writes these params to a swagger request
func (o *GetRunsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Pipelines != nil {

		// query param pipelines
		var qrPipelines string

		if o.Pipelines != nil {
			qrPipelines = *o.Pipelines
		}
		qPipelines := qrPipelines
		if qPipelines != "" {

			if err := r.SetQueryParam("pipelines", qPipelines); err != nil {
				return err
			}
		}
	}

	if o.Statuses != nil {

		// query param statuses
		var qrStatuses string

		if o.Statuses != nil {
			qrStatuses = *o.Statuses
		}
		qStatuses := qrStatuses
		if qStatuses != "" {

			if err := r.SetQueryParam("statuses", qStatuses); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
