// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// NewPostRunsStartParams creates a new PostRunsStartParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRunsStartParams() *PostRunsStartParams {
	return &PostRunsStartParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRunsStartParamsWithTimeout creates a new PostRunsStartParams object
// with the ability to set a timeout on a request.
func NewPostRunsStartParamsWithTimeout(timeout time.Duration) *PostRunsStartParams {
	return &PostRunsStartParams{
		timeout: timeout,
	}
}

// NewPostRunsStartParamsWithContext creates a new PostRunsStartParams object
// with the ability to set a context for a request.
func NewPostRunsStartParamsWithContext(ctx context.Context) *PostRunsStartParams {
	return &PostRunsStartParams{
		Context: ctx,
	}
}

// NewPostRunsStartParamsWithHTTPClient creates a new PostRunsStartParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRunsStartParamsWithHTTPClient(client *http.Client) *PostRunsStartParams {
	return &PostRunsStartParams{
		HTTPClient: client,
	}
}

/*
PostRunsStartParams contains all the parameters to send to the API endpoint

	for the post runs start operation.

	Typically these are written to a http.Request.
*/
type PostRunsStartParams struct {

	/* Request.

	   Start run request
	*/
	Request *models.V1RunsStartRunRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post runs start params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRunsStartParams) WithDefaults() *PostRunsStartParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post runs start params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRunsStartParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post runs start params
func (o *PostRunsStartParams) WithTimeout(timeout time.Duration) *PostRunsStartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post runs start params
func (o *PostRunsStartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post runs start params
func (o *PostRunsStartParams) WithContext(ctx context.Context) *PostRunsStartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post runs start params
func (o *PostRunsStartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post runs start params
func (o *PostRunsStartParams) WithHTTPClient(client *http.Client) *PostRunsStartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post runs start params
func (o *PostRunsStartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post runs start params
func (o *PostRunsStartParams) WithRequest(request *models.V1RunsStartRunRequest) *PostRunsStartParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post runs start params
func (o *PostRunsStartParams) SetRequest(request *models.V1RunsStartRunRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostRunsStartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
