// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// GetAPIV1PluginsAwsCredentialsStatusReader is a Reader for the GetAPIV1PluginsAwsCredentialsStatus structure.
type GetAPIV1PluginsAwsCredentialsStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1PluginsAwsCredentialsStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1PluginsAwsCredentialsStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/plugins/aws/credentials/status] GetAPIV1PluginsAwsCredentialsStatus", response, response.Code())
	}
}

// NewGetAPIV1PluginsAwsCredentialsStatusOK creates a GetAPIV1PluginsAwsCredentialsStatusOK with default headers values
func NewGetAPIV1PluginsAwsCredentialsStatusOK() *GetAPIV1PluginsAwsCredentialsStatusOK {
	return &GetAPIV1PluginsAwsCredentialsStatusOK{}
}

/*
GetAPIV1PluginsAwsCredentialsStatusOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1PluginsAwsCredentialsStatusOK struct {
	Payload *models.PluginAWSCredentialStatus
}

// IsSuccess returns true when this get Api v1 plugins aws credentials status o k response has a 2xx status code
func (o *GetAPIV1PluginsAwsCredentialsStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 plugins aws credentials status o k response has a 3xx status code
func (o *GetAPIV1PluginsAwsCredentialsStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 plugins aws credentials status o k response has a 4xx status code
func (o *GetAPIV1PluginsAwsCredentialsStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 plugins aws credentials status o k response has a 5xx status code
func (o *GetAPIV1PluginsAwsCredentialsStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 plugins aws credentials status o k response a status code equal to that given
func (o *GetAPIV1PluginsAwsCredentialsStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 plugins aws credentials status o k response
func (o *GetAPIV1PluginsAwsCredentialsStatusOK) Code() int {
	return 200
}

func (o *GetAPIV1PluginsAwsCredentialsStatusOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/plugins/aws/credentials/status][%d] getApiV1PluginsAwsCredentialsStatusOK %s", 200, payload)
}

func (o *GetAPIV1PluginsAwsCredentialsStatusOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/plugins/aws/credentials/status][%d] getApiV1PluginsAwsCredentialsStatusOK %s", 200, payload)
}

func (o *GetAPIV1PluginsAwsCredentialsStatusOK) GetPayload() *models.PluginAWSCredentialStatus {
	return o.Payload
}

func (o *GetAPIV1PluginsAwsCredentialsStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PluginAWSCredentialStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
