// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// NewDeleteAssetsIDTermsParams creates a new DeleteAssetsIDTermsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAssetsIDTermsParams() *DeleteAssetsIDTermsParams {
	return &DeleteAssetsIDTermsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAssetsIDTermsParamsWithTimeout creates a new DeleteAssetsIDTermsParams object
// with the ability to set a timeout on a request.
func NewDeleteAssetsIDTermsParamsWithTimeout(timeout time.Duration) *DeleteAssetsIDTermsParams {
	return &DeleteAssetsIDTermsParams{
		timeout: timeout,
	}
}

// NewDeleteAssetsIDTermsParamsWithContext creates a new DeleteAssetsIDTermsParams object
// with the ability to set a context for a request.
func NewDeleteAssetsIDTermsParamsWithContext(ctx context.Context) *DeleteAssetsIDTermsParams {
	return &DeleteAssetsIDTermsParams{
		Context: ctx,
	}
}

// NewDeleteAssetsIDTermsParamsWithHTTPClient creates a new DeleteAssetsIDTermsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAssetsIDTermsParamsWithHTTPClient(client *http.Client) *DeleteAssetsIDTermsParams {
	return &DeleteAssetsIDTermsParams{
		HTTPClient: client,
	}
}

/*
DeleteAssetsIDTermsParams contains all the parameters to send to the API endpoint

	for the delete assets ID terms operation.

	Typically these are written to a http.Request.
*/
type DeleteAssetsIDTermsParams struct {

	/* ID.

	   Asset ID
	*/
	ID string

	/* Term.

	   Term ID to remove
	*/
	Term *models.V1AssetsRemoveTermRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete assets ID terms params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAssetsIDTermsParams) WithDefaults() *DeleteAssetsIDTermsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete assets ID terms params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAssetsIDTermsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete assets ID terms params
func (o *DeleteAssetsIDTermsParams) WithTimeout(timeout time.Duration) *DeleteAssetsIDTermsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete assets ID terms params
func (o *DeleteAssetsIDTermsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete assets ID terms params
func (o *DeleteAssetsIDTermsParams) WithContext(ctx context.Context) *DeleteAssetsIDTermsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete assets ID terms params
func (o *DeleteAssetsIDTermsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete assets ID terms params
func (o *DeleteAssetsIDTermsParams) WithHTTPClient(client *http.Client) *DeleteAssetsIDTermsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete assets ID terms params
func (o *DeleteAssetsIDTermsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete assets ID terms params
func (o *DeleteAssetsIDTermsParams) WithID(id string) *DeleteAssetsIDTermsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete assets ID terms params
func (o *DeleteAssetsIDTermsParams) SetID(id string) {
	o.ID = id
}

// WithTerm adds the term to the delete assets ID terms params
func (o *DeleteAssetsIDTermsParams) WithTerm(term *models.V1AssetsRemoveTermRequest) *DeleteAssetsIDTermsParams {
	o.SetTerm(term)
	return o
}

// SetTerm adds the term to the delete assets ID terms params
func (o *DeleteAssetsIDTermsParams) SetTerm(term *models.V1AssetsRemoveTermRequest) {
	o.Term = term
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAssetsIDTermsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Term != nil {
		if err := r.SetBodyParam(o.Term); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
