// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// GetAssetsLookupTypeServiceNameReader is a Reader for the GetAssetsLookupTypeServiceName structure.
type GetAssetsLookupTypeServiceNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAssetsLookupTypeServiceNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAssetsLookupTypeServiceNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetAssetsLookupTypeServiceNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAssetsLookupTypeServiceNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /assets/lookup/{type}/{service}/{name}] GetAssetsLookupTypeServiceName", response, response.Code())
	}
}

// NewGetAssetsLookupTypeServiceNameOK creates a GetAssetsLookupTypeServiceNameOK with default headers values
func NewGetAssetsLookupTypeServiceNameOK() *GetAssetsLookupTypeServiceNameOK {
	return &GetAssetsLookupTypeServiceNameOK{}
}

/*
GetAssetsLookupTypeServiceNameOK describes a response with status code 200, with default header values.

OK
*/
type GetAssetsLookupTypeServiceNameOK struct {
	Payload *models.AssetAsset
}

// IsSuccess returns true when this get assets lookup type service name o k response has a 2xx status code
func (o *GetAssetsLookupTypeServiceNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get assets lookup type service name o k response has a 3xx status code
func (o *GetAssetsLookupTypeServiceNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets lookup type service name o k response has a 4xx status code
func (o *GetAssetsLookupTypeServiceNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get assets lookup type service name o k response has a 5xx status code
func (o *GetAssetsLookupTypeServiceNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get assets lookup type service name o k response a status code equal to that given
func (o *GetAssetsLookupTypeServiceNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get assets lookup type service name o k response
func (o *GetAssetsLookupTypeServiceNameOK) Code() int {
	return 200
}

func (o *GetAssetsLookupTypeServiceNameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/lookup/{type}/{service}/{name}][%d] getAssetsLookupTypeServiceNameOK %s", 200, payload)
}

func (o *GetAssetsLookupTypeServiceNameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/lookup/{type}/{service}/{name}][%d] getAssetsLookupTypeServiceNameOK %s", 200, payload)
}

func (o *GetAssetsLookupTypeServiceNameOK) GetPayload() *models.AssetAsset {
	return o.Payload
}

func (o *GetAssetsLookupTypeServiceNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssetAsset)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssetsLookupTypeServiceNameNotFound creates a GetAssetsLookupTypeServiceNameNotFound with default headers values
func NewGetAssetsLookupTypeServiceNameNotFound() *GetAssetsLookupTypeServiceNameNotFound {
	return &GetAssetsLookupTypeServiceNameNotFound{}
}

/*
GetAssetsLookupTypeServiceNameNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAssetsLookupTypeServiceNameNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get assets lookup type service name not found response has a 2xx status code
func (o *GetAssetsLookupTypeServiceNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get assets lookup type service name not found response has a 3xx status code
func (o *GetAssetsLookupTypeServiceNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets lookup type service name not found response has a 4xx status code
func (o *GetAssetsLookupTypeServiceNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get assets lookup type service name not found response has a 5xx status code
func (o *GetAssetsLookupTypeServiceNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get assets lookup type service name not found response a status code equal to that given
func (o *GetAssetsLookupTypeServiceNameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get assets lookup type service name not found response
func (o *GetAssetsLookupTypeServiceNameNotFound) Code() int {
	return 404
}

func (o *GetAssetsLookupTypeServiceNameNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/lookup/{type}/{service}/{name}][%d] getAssetsLookupTypeServiceNameNotFound %s", 404, payload)
}

func (o *GetAssetsLookupTypeServiceNameNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/lookup/{type}/{service}/{name}][%d] getAssetsLookupTypeServiceNameNotFound %s", 404, payload)
}

func (o *GetAssetsLookupTypeServiceNameNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetsLookupTypeServiceNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssetsLookupTypeServiceNameInternalServerError creates a GetAssetsLookupTypeServiceNameInternalServerError with default headers values
func NewGetAssetsLookupTypeServiceNameInternalServerError() *GetAssetsLookupTypeServiceNameInternalServerError {
	return &GetAssetsLookupTypeServiceNameInternalServerError{}
}

/*
GetAssetsLookupTypeServiceNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAssetsLookupTypeServiceNameInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get assets lookup type service name internal server error response has a 2xx status code
func (o *GetAssetsLookupTypeServiceNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get assets lookup type service name internal server error response has a 3xx status code
func (o *GetAssetsLookupTypeServiceNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets lookup type service name internal server error response has a 4xx status code
func (o *GetAssetsLookupTypeServiceNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get assets lookup type service name internal server error response has a 5xx status code
func (o *GetAssetsLookupTypeServiceNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get assets lookup type service name internal server error response a status code equal to that given
func (o *GetAssetsLookupTypeServiceNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get assets lookup type service name internal server error response
func (o *GetAssetsLookupTypeServiceNameInternalServerError) Code() int {
	return 500
}

func (o *GetAssetsLookupTypeServiceNameInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/lookup/{type}/{service}/{name}][%d] getAssetsLookupTypeServiceNameInternalServerError %s", 500, payload)
}

func (o *GetAssetsLookupTypeServiceNameInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/lookup/{type}/{service}/{name}][%d] getAssetsLookupTypeServiceNameInternalServerError %s", 500, payload)
}

func (o *GetAssetsLookupTypeServiceNameInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetsLookupTypeServiceNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
