// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAssetsSuggestionsMetadataValuesParams creates a new GetAssetsSuggestionsMetadataValuesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetsSuggestionsMetadataValuesParams() *GetAssetsSuggestionsMetadataValuesParams {
	return &GetAssetsSuggestionsMetadataValuesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetsSuggestionsMetadataValuesParamsWithTimeout creates a new GetAssetsSuggestionsMetadataValuesParams object
// with the ability to set a timeout on a request.
func NewGetAssetsSuggestionsMetadataValuesParamsWithTimeout(timeout time.Duration) *GetAssetsSuggestionsMetadataValuesParams {
	return &GetAssetsSuggestionsMetadataValuesParams{
		timeout: timeout,
	}
}

// NewGetAssetsSuggestionsMetadataValuesParamsWithContext creates a new GetAssetsSuggestionsMetadataValuesParams object
// with the ability to set a context for a request.
func NewGetAssetsSuggestionsMetadataValuesParamsWithContext(ctx context.Context) *GetAssetsSuggestionsMetadataValuesParams {
	return &GetAssetsSuggestionsMetadataValuesParams{
		Context: ctx,
	}
}

// NewGetAssetsSuggestionsMetadataValuesParamsWithHTTPClient creates a new GetAssetsSuggestionsMetadataValuesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetsSuggestionsMetadataValuesParamsWithHTTPClient(client *http.Client) *GetAssetsSuggestionsMetadataValuesParams {
	return &GetAssetsSuggestionsMetadataValuesParams{
		HTTPClient: client,
	}
}

/*
GetAssetsSuggestionsMetadataValuesParams contains all the parameters to send to the API endpoint

	for the get assets suggestions metadata values operation.

	Typically these are written to a http.Request.
*/
type GetAssetsSuggestionsMetadataValuesParams struct {

	/* Field.

	   Metadata field name
	*/
	Field string

	/* Limit.

	   Maximum number of suggestions

	   Default: 10
	*/
	Limit *int64

	/* Prefix.

	   Value prefix to filter by
	*/
	Prefix *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get assets suggestions metadata values params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsSuggestionsMetadataValuesParams) WithDefaults() *GetAssetsSuggestionsMetadataValuesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get assets suggestions metadata values params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsSuggestionsMetadataValuesParams) SetDefaults() {
	var (
		limitDefault = int64(10)
	)

	val := GetAssetsSuggestionsMetadataValuesParams{
		Limit: &limitDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) WithTimeout(timeout time.Duration) *GetAssetsSuggestionsMetadataValuesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) WithContext(ctx context.Context) *GetAssetsSuggestionsMetadataValuesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) WithHTTPClient(client *http.Client) *GetAssetsSuggestionsMetadataValuesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithField adds the field to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) WithField(field string) *GetAssetsSuggestionsMetadataValuesParams {
	o.SetField(field)
	return o
}

// SetField adds the field to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) SetField(field string) {
	o.Field = field
}

// WithLimit adds the limit to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) WithLimit(limit *int64) *GetAssetsSuggestionsMetadataValuesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPrefix adds the prefix to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) WithPrefix(prefix *string) *GetAssetsSuggestionsMetadataValuesParams {
	o.SetPrefix(prefix)
	return o
}

// SetPrefix adds the prefix to the get assets suggestions metadata values params
func (o *GetAssetsSuggestionsMetadataValuesParams) SetPrefix(prefix *string) {
	o.Prefix = prefix
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetsSuggestionsMetadataValuesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param field
	qrField := o.Field
	qField := qrField
	if qField != "" {

		if err := r.SetQueryParam("field", qField); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Prefix != nil {

		// query param prefix
		var qrPrefix string

		if o.Prefix != nil {
			qrPrefix = *o.Prefix
		}
		qPrefix := qrPrefix
		if qPrefix != "" {

			if err := r.SetQueryParam("prefix", qPrefix); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
