// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// GetAssetsMatchPatternReader is a Reader for the GetAssetsMatchPattern structure.
type GetAssetsMatchPatternReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAssetsMatchPatternReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAssetsMatchPatternOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAssetsMatchPatternBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAssetsMatchPatternInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /assets/match-pattern] GetAssetsMatchPattern", response, response.Code())
	}
}

// NewGetAssetsMatchPatternOK creates a GetAssetsMatchPatternOK with default headers values
func NewGetAssetsMatchPatternOK() *GetAssetsMatchPatternOK {
	return &GetAssetsMatchPatternOK{}
}

/*
GetAssetsMatchPatternOK describes a response with status code 200, with default header values.

OK
*/
type GetAssetsMatchPatternOK struct {
	Payload []*models.AssetAsset
}

// IsSuccess returns true when this get assets match pattern o k response has a 2xx status code
func (o *GetAssetsMatchPatternOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get assets match pattern o k response has a 3xx status code
func (o *GetAssetsMatchPatternOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets match pattern o k response has a 4xx status code
func (o *GetAssetsMatchPatternOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get assets match pattern o k response has a 5xx status code
func (o *GetAssetsMatchPatternOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get assets match pattern o k response a status code equal to that given
func (o *GetAssetsMatchPatternOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get assets match pattern o k response
func (o *GetAssetsMatchPatternOK) Code() int {
	return 200
}

func (o *GetAssetsMatchPatternOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/match-pattern][%d] getAssetsMatchPatternOK %s", 200, payload)
}

func (o *GetAssetsMatchPatternOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/match-pattern][%d] getAssetsMatchPatternOK %s", 200, payload)
}

func (o *GetAssetsMatchPatternOK) GetPayload() []*models.AssetAsset {
	return o.Payload
}

func (o *GetAssetsMatchPatternOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssetsMatchPatternBadRequest creates a GetAssetsMatchPatternBadRequest with default headers values
func NewGetAssetsMatchPatternBadRequest() *GetAssetsMatchPatternBadRequest {
	return &GetAssetsMatchPatternBadRequest{}
}

/*
GetAssetsMatchPatternBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAssetsMatchPatternBadRequest struct {
	Payload *models.CommonErrorResponse
}

// IsSuccess returns true when this get assets match pattern bad request response has a 2xx status code
func (o *GetAssetsMatchPatternBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get assets match pattern bad request response has a 3xx status code
func (o *GetAssetsMatchPatternBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets match pattern bad request response has a 4xx status code
func (o *GetAssetsMatchPatternBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get assets match pattern bad request response has a 5xx status code
func (o *GetAssetsMatchPatternBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get assets match pattern bad request response a status code equal to that given
func (o *GetAssetsMatchPatternBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get assets match pattern bad request response
func (o *GetAssetsMatchPatternBadRequest) Code() int {
	return 400
}

func (o *GetAssetsMatchPatternBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/match-pattern][%d] getAssetsMatchPatternBadRequest %s", 400, payload)
}

func (o *GetAssetsMatchPatternBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/match-pattern][%d] getAssetsMatchPatternBadRequest %s", 400, payload)
}

func (o *GetAssetsMatchPatternBadRequest) GetPayload() *models.CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetsMatchPatternBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssetsMatchPatternInternalServerError creates a GetAssetsMatchPatternInternalServerError with default headers values
func NewGetAssetsMatchPatternInternalServerError() *GetAssetsMatchPatternInternalServerError {
	return &GetAssetsMatchPatternInternalServerError{}
}

/*
GetAssetsMatchPatternInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAssetsMatchPatternInternalServerError struct {
	Payload *models.CommonErrorResponse
}

// IsSuccess returns true when this get assets match pattern internal server error response has a 2xx status code
func (o *GetAssetsMatchPatternInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get assets match pattern internal server error response has a 3xx status code
func (o *GetAssetsMatchPatternInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets match pattern internal server error response has a 4xx status code
func (o *GetAssetsMatchPatternInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get assets match pattern internal server error response has a 5xx status code
func (o *GetAssetsMatchPatternInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get assets match pattern internal server error response a status code equal to that given
func (o *GetAssetsMatchPatternInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get assets match pattern internal server error response
func (o *GetAssetsMatchPatternInternalServerError) Code() int {
	return 500
}

func (o *GetAssetsMatchPatternInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/match-pattern][%d] getAssetsMatchPatternInternalServerError %s", 500, payload)
}

func (o *GetAssetsMatchPatternInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/match-pattern][%d] getAssetsMatchPatternInternalServerError %s", 500, payload)
}

func (o *GetAssetsMatchPatternInternalServerError) GetPayload() *models.CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetsMatchPatternInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
