// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAssetsSuggestionsMetadataFieldsParams creates a new GetAssetsSuggestionsMetadataFieldsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetsSuggestionsMetadataFieldsParams() *GetAssetsSuggestionsMetadataFieldsParams {
	return &GetAssetsSuggestionsMetadataFieldsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetsSuggestionsMetadataFieldsParamsWithTimeout creates a new GetAssetsSuggestionsMetadataFieldsParams object
// with the ability to set a timeout on a request.
func NewGetAssetsSuggestionsMetadataFieldsParamsWithTimeout(timeout time.Duration) *GetAssetsSuggestionsMetadataFieldsParams {
	return &GetAssetsSuggestionsMetadataFieldsParams{
		timeout: timeout,
	}
}

// NewGetAssetsSuggestionsMetadataFieldsParamsWithContext creates a new GetAssetsSuggestionsMetadataFieldsParams object
// with the ability to set a context for a request.
func NewGetAssetsSuggestionsMetadataFieldsParamsWithContext(ctx context.Context) *GetAssetsSuggestionsMetadataFieldsParams {
	return &GetAssetsSuggestionsMetadataFieldsParams{
		Context: ctx,
	}
}

// NewGetAssetsSuggestionsMetadataFieldsParamsWithHTTPClient creates a new GetAssetsSuggestionsMetadataFieldsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetsSuggestionsMetadataFieldsParamsWithHTTPClient(client *http.Client) *GetAssetsSuggestionsMetadataFieldsParams {
	return &GetAssetsSuggestionsMetadataFieldsParams{
		HTTPClient: client,
	}
}

/*
GetAssetsSuggestionsMetadataFieldsParams contains all the parameters to send to the API endpoint

	for the get assets suggestions metadata fields operation.

	Typically these are written to a http.Request.
*/
type GetAssetsSuggestionsMetadataFieldsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get assets suggestions metadata fields params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsSuggestionsMetadataFieldsParams) WithDefaults() *GetAssetsSuggestionsMetadataFieldsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get assets suggestions metadata fields params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsSuggestionsMetadataFieldsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get assets suggestions metadata fields params
func (o *GetAssetsSuggestionsMetadataFieldsParams) WithTimeout(timeout time.Duration) *GetAssetsSuggestionsMetadataFieldsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get assets suggestions metadata fields params
func (o *GetAssetsSuggestionsMetadataFieldsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get assets suggestions metadata fields params
func (o *GetAssetsSuggestionsMetadataFieldsParams) WithContext(ctx context.Context) *GetAssetsSuggestionsMetadataFieldsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get assets suggestions metadata fields params
func (o *GetAssetsSuggestionsMetadataFieldsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get assets suggestions metadata fields params
func (o *GetAssetsSuggestionsMetadataFieldsParams) WithHTTPClient(client *http.Client) *GetAssetsSuggestionsMetadataFieldsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get assets suggestions metadata fields params
func (o *GetAssetsSuggestionsMetadataFieldsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetsSuggestionsMetadataFieldsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
