// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAssetsByGlossaryTermTermIDParams creates a new GetAssetsByGlossaryTermTermIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetsByGlossaryTermTermIDParams() *GetAssetsByGlossaryTermTermIDParams {
	return &GetAssetsByGlossaryTermTermIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetsByGlossaryTermTermIDParamsWithTimeout creates a new GetAssetsByGlossaryTermTermIDParams object
// with the ability to set a timeout on a request.
func NewGetAssetsByGlossaryTermTermIDParamsWithTimeout(timeout time.Duration) *GetAssetsByGlossaryTermTermIDParams {
	return &GetAssetsByGlossaryTermTermIDParams{
		timeout: timeout,
	}
}

// NewGetAssetsByGlossaryTermTermIDParamsWithContext creates a new GetAssetsByGlossaryTermTermIDParams object
// with the ability to set a context for a request.
func NewGetAssetsByGlossaryTermTermIDParamsWithContext(ctx context.Context) *GetAssetsByGlossaryTermTermIDParams {
	return &GetAssetsByGlossaryTermTermIDParams{
		Context: ctx,
	}
}

// NewGetAssetsByGlossaryTermTermIDParamsWithHTTPClient creates a new GetAssetsByGlossaryTermTermIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetsByGlossaryTermTermIDParamsWithHTTPClient(client *http.Client) *GetAssetsByGlossaryTermTermIDParams {
	return &GetAssetsByGlossaryTermTermIDParams{
		HTTPClient: client,
	}
}

/*
GetAssetsByGlossaryTermTermIDParams contains all the parameters to send to the API endpoint

	for the get assets by glossary term term ID operation.

	Typically these are written to a http.Request.
*/
type GetAssetsByGlossaryTermTermIDParams struct {

	/* Limit.

	   Maximum number of assets

	   Default: 20
	*/
	Limit *int64

	/* Offset.

	   Pagination offset
	*/
	Offset *int64

	/* TermID.

	   Glossary Term ID
	*/
	TermID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get assets by glossary term term ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsByGlossaryTermTermIDParams) WithDefaults() *GetAssetsByGlossaryTermTermIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get assets by glossary term term ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsByGlossaryTermTermIDParams) SetDefaults() {
	var (
		limitDefault = int64(20)

		offsetDefault = int64(0)
	)

	val := GetAssetsByGlossaryTermTermIDParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) WithTimeout(timeout time.Duration) *GetAssetsByGlossaryTermTermIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) WithContext(ctx context.Context) *GetAssetsByGlossaryTermTermIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) WithHTTPClient(client *http.Client) *GetAssetsByGlossaryTermTermIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) WithLimit(limit *int64) *GetAssetsByGlossaryTermTermIDParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) WithOffset(offset *int64) *GetAssetsByGlossaryTermTermIDParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithTermID adds the termID to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) WithTermID(termID string) *GetAssetsByGlossaryTermTermIDParams {
	o.SetTermID(termID)
	return o
}

// SetTermID adds the termId to the get assets by glossary term term ID params
func (o *GetAssetsByGlossaryTermTermIDParams) SetTermID(termID string) {
	o.TermID = termID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetsByGlossaryTermTermIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	// path param term_id
	if err := r.SetPathParam("term_id", o.TermID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
