// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// GetAssetsSuggestionsTagsReader is a Reader for the GetAssetsSuggestionsTags structure.
type GetAssetsSuggestionsTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAssetsSuggestionsTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAssetsSuggestionsTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAssetsSuggestionsTagsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /assets/suggestions/tags] GetAssetsSuggestionsTags", response, response.Code())
	}
}

// NewGetAssetsSuggestionsTagsOK creates a GetAssetsSuggestionsTagsOK with default headers values
func NewGetAssetsSuggestionsTagsOK() *GetAssetsSuggestionsTagsOK {
	return &GetAssetsSuggestionsTagsOK{}
}

/*
GetAssetsSuggestionsTagsOK describes a response with status code 200, with default header values.

OK
*/
type GetAssetsSuggestionsTagsOK struct {
	Payload []string
}

// IsSuccess returns true when this get assets suggestions tags o k response has a 2xx status code
func (o *GetAssetsSuggestionsTagsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get assets suggestions tags o k response has a 3xx status code
func (o *GetAssetsSuggestionsTagsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets suggestions tags o k response has a 4xx status code
func (o *GetAssetsSuggestionsTagsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get assets suggestions tags o k response has a 5xx status code
func (o *GetAssetsSuggestionsTagsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get assets suggestions tags o k response a status code equal to that given
func (o *GetAssetsSuggestionsTagsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get assets suggestions tags o k response
func (o *GetAssetsSuggestionsTagsOK) Code() int {
	return 200
}

func (o *GetAssetsSuggestionsTagsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/suggestions/tags][%d] getAssetsSuggestionsTagsOK %s", 200, payload)
}

func (o *GetAssetsSuggestionsTagsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/suggestions/tags][%d] getAssetsSuggestionsTagsOK %s", 200, payload)
}

func (o *GetAssetsSuggestionsTagsOK) GetPayload() []string {
	return o.Payload
}

func (o *GetAssetsSuggestionsTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssetsSuggestionsTagsInternalServerError creates a GetAssetsSuggestionsTagsInternalServerError with default headers values
func NewGetAssetsSuggestionsTagsInternalServerError() *GetAssetsSuggestionsTagsInternalServerError {
	return &GetAssetsSuggestionsTagsInternalServerError{}
}

/*
GetAssetsSuggestionsTagsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAssetsSuggestionsTagsInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get assets suggestions tags internal server error response has a 2xx status code
func (o *GetAssetsSuggestionsTagsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get assets suggestions tags internal server error response has a 3xx status code
func (o *GetAssetsSuggestionsTagsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets suggestions tags internal server error response has a 4xx status code
func (o *GetAssetsSuggestionsTagsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get assets suggestions tags internal server error response has a 5xx status code
func (o *GetAssetsSuggestionsTagsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get assets suggestions tags internal server error response a status code equal to that given
func (o *GetAssetsSuggestionsTagsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get assets suggestions tags internal server error response
func (o *GetAssetsSuggestionsTagsInternalServerError) Code() int {
	return 500
}

func (o *GetAssetsSuggestionsTagsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/suggestions/tags][%d] getAssetsSuggestionsTagsInternalServerError %s", 500, payload)
}

func (o *GetAssetsSuggestionsTagsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/suggestions/tags][%d] getAssetsSuggestionsTagsInternalServerError %s", 500, payload)
}

func (o *GetAssetsSuggestionsTagsInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetsSuggestionsTagsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
