// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAssetsIDRunHistoryHistogramParams creates a new GetAssetsIDRunHistoryHistogramParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetsIDRunHistoryHistogramParams() *GetAssetsIDRunHistoryHistogramParams {
	return &GetAssetsIDRunHistoryHistogramParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetsIDRunHistoryHistogramParamsWithTimeout creates a new GetAssetsIDRunHistoryHistogramParams object
// with the ability to set a timeout on a request.
func NewGetAssetsIDRunHistoryHistogramParamsWithTimeout(timeout time.Duration) *GetAssetsIDRunHistoryHistogramParams {
	return &GetAssetsIDRunHistoryHistogramParams{
		timeout: timeout,
	}
}

// NewGetAssetsIDRunHistoryHistogramParamsWithContext creates a new GetAssetsIDRunHistoryHistogramParams object
// with the ability to set a context for a request.
func NewGetAssetsIDRunHistoryHistogramParamsWithContext(ctx context.Context) *GetAssetsIDRunHistoryHistogramParams {
	return &GetAssetsIDRunHistoryHistogramParams{
		Context: ctx,
	}
}

// NewGetAssetsIDRunHistoryHistogramParamsWithHTTPClient creates a new GetAssetsIDRunHistoryHistogramParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetsIDRunHistoryHistogramParamsWithHTTPClient(client *http.Client) *GetAssetsIDRunHistoryHistogramParams {
	return &GetAssetsIDRunHistoryHistogramParams{
		HTTPClient: client,
	}
}

/*
GetAssetsIDRunHistoryHistogramParams contains all the parameters to send to the API endpoint

	for the get assets ID run history histogram operation.

	Typically these are written to a http.Request.
*/
type GetAssetsIDRunHistoryHistogramParams struct {

	/* ID.

	   Asset ID
	*/
	ID string

	/* Period.

	   Time period (7d, 30d, 90d)

	   Default: "30d"
	*/
	Period *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get assets ID run history histogram params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsIDRunHistoryHistogramParams) WithDefaults() *GetAssetsIDRunHistoryHistogramParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get assets ID run history histogram params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsIDRunHistoryHistogramParams) SetDefaults() {
	var (
		periodDefault = string("30d")
	)

	val := GetAssetsIDRunHistoryHistogramParams{
		Period: &periodDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get assets ID run history histogram params
func (o *GetAssetsIDRunHistoryHistogramParams) WithTimeout(timeout time.Duration) *GetAssetsIDRunHistoryHistogramParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get assets ID run history histogram params
func (o *GetAssetsIDRunHistoryHistogramParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get assets ID run history histogram params
func (o *GetAssetsIDRunHistoryHistogramParams) WithContext(ctx context.Context) *GetAssetsIDRunHistoryHistogramParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get assets ID run history histogram params
func (o *GetAssetsIDRunHistoryHistogramParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get assets ID run history histogram params
func (o *GetAssetsIDRunHistoryHistogramParams) WithHTTPClient(client *http.Client) *GetAssetsIDRunHistoryHistogramParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get assets ID run history histogram params
func (o *GetAssetsIDRunHistoryHistogramParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get assets ID run history histogram params
func (o *GetAssetsIDRunHistoryHistogramParams) WithID(id string) *GetAssetsIDRunHistoryHistogramParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get assets ID run history histogram params
func (o *GetAssetsIDRunHistoryHistogramParams) SetID(id string) {
	o.ID = id
}

// WithPeriod adds the period to the get assets ID run history histogram params
func (o *GetAssetsIDRunHistoryHistogramParams) WithPeriod(period *string) *GetAssetsIDRunHistoryHistogramParams {
	o.SetPeriod(period)
	return o
}

// SetPeriod adds the period to the get assets ID run history histogram params
func (o *GetAssetsIDRunHistoryHistogramParams) SetPeriod(period *string) {
	o.Period = period
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetsIDRunHistoryHistogramParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Period != nil {

		// query param period
		var qrPeriod string

		if o.Period != nil {
			qrPeriod = *o.Period
		}
		qPeriod := qrPeriod
		if qPeriod != "" {

			if err := r.SetQueryParam("period", qPeriod); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
