// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// GetAssetsIDRunHistoryHistogramReader is a Reader for the GetAssetsIDRunHistoryHistogram structure.
type GetAssetsIDRunHistoryHistogramReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAssetsIDRunHistoryHistogramReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAssetsIDRunHistoryHistogramOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAssetsIDRunHistoryHistogramBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAssetsIDRunHistoryHistogramNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAssetsIDRunHistoryHistogramInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /assets/{id}/run-history/histogram] GetAssetsIDRunHistoryHistogram", response, response.Code())
	}
}

// NewGetAssetsIDRunHistoryHistogramOK creates a GetAssetsIDRunHistoryHistogramOK with default headers values
func NewGetAssetsIDRunHistoryHistogramOK() *GetAssetsIDRunHistoryHistogramOK {
	return &GetAssetsIDRunHistoryHistogramOK{}
}

/*
GetAssetsIDRunHistoryHistogramOK describes a response with status code 200, with default header values.

OK
*/
type GetAssetsIDRunHistoryHistogramOK struct {
	Payload *models.V1AssetsHistogramResponse
}

// IsSuccess returns true when this get assets Id run history histogram o k response has a 2xx status code
func (o *GetAssetsIDRunHistoryHistogramOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get assets Id run history histogram o k response has a 3xx status code
func (o *GetAssetsIDRunHistoryHistogramOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets Id run history histogram o k response has a 4xx status code
func (o *GetAssetsIDRunHistoryHistogramOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get assets Id run history histogram o k response has a 5xx status code
func (o *GetAssetsIDRunHistoryHistogramOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get assets Id run history histogram o k response a status code equal to that given
func (o *GetAssetsIDRunHistoryHistogramOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get assets Id run history histogram o k response
func (o *GetAssetsIDRunHistoryHistogramOK) Code() int {
	return 200
}

func (o *GetAssetsIDRunHistoryHistogramOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/{id}/run-history/histogram][%d] getAssetsIdRunHistoryHistogramOK %s", 200, payload)
}

func (o *GetAssetsIDRunHistoryHistogramOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/{id}/run-history/histogram][%d] getAssetsIdRunHistoryHistogramOK %s", 200, payload)
}

func (o *GetAssetsIDRunHistoryHistogramOK) GetPayload() *models.V1AssetsHistogramResponse {
	return o.Payload
}

func (o *GetAssetsIDRunHistoryHistogramOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1AssetsHistogramResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssetsIDRunHistoryHistogramBadRequest creates a GetAssetsIDRunHistoryHistogramBadRequest with default headers values
func NewGetAssetsIDRunHistoryHistogramBadRequest() *GetAssetsIDRunHistoryHistogramBadRequest {
	return &GetAssetsIDRunHistoryHistogramBadRequest{}
}

/*
GetAssetsIDRunHistoryHistogramBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAssetsIDRunHistoryHistogramBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get assets Id run history histogram bad request response has a 2xx status code
func (o *GetAssetsIDRunHistoryHistogramBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get assets Id run history histogram bad request response has a 3xx status code
func (o *GetAssetsIDRunHistoryHistogramBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets Id run history histogram bad request response has a 4xx status code
func (o *GetAssetsIDRunHistoryHistogramBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get assets Id run history histogram bad request response has a 5xx status code
func (o *GetAssetsIDRunHistoryHistogramBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get assets Id run history histogram bad request response a status code equal to that given
func (o *GetAssetsIDRunHistoryHistogramBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get assets Id run history histogram bad request response
func (o *GetAssetsIDRunHistoryHistogramBadRequest) Code() int {
	return 400
}

func (o *GetAssetsIDRunHistoryHistogramBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/{id}/run-history/histogram][%d] getAssetsIdRunHistoryHistogramBadRequest %s", 400, payload)
}

func (o *GetAssetsIDRunHistoryHistogramBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/{id}/run-history/histogram][%d] getAssetsIdRunHistoryHistogramBadRequest %s", 400, payload)
}

func (o *GetAssetsIDRunHistoryHistogramBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetsIDRunHistoryHistogramBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssetsIDRunHistoryHistogramNotFound creates a GetAssetsIDRunHistoryHistogramNotFound with default headers values
func NewGetAssetsIDRunHistoryHistogramNotFound() *GetAssetsIDRunHistoryHistogramNotFound {
	return &GetAssetsIDRunHistoryHistogramNotFound{}
}

/*
GetAssetsIDRunHistoryHistogramNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAssetsIDRunHistoryHistogramNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get assets Id run history histogram not found response has a 2xx status code
func (o *GetAssetsIDRunHistoryHistogramNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get assets Id run history histogram not found response has a 3xx status code
func (o *GetAssetsIDRunHistoryHistogramNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets Id run history histogram not found response has a 4xx status code
func (o *GetAssetsIDRunHistoryHistogramNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get assets Id run history histogram not found response has a 5xx status code
func (o *GetAssetsIDRunHistoryHistogramNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get assets Id run history histogram not found response a status code equal to that given
func (o *GetAssetsIDRunHistoryHistogramNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get assets Id run history histogram not found response
func (o *GetAssetsIDRunHistoryHistogramNotFound) Code() int {
	return 404
}

func (o *GetAssetsIDRunHistoryHistogramNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/{id}/run-history/histogram][%d] getAssetsIdRunHistoryHistogramNotFound %s", 404, payload)
}

func (o *GetAssetsIDRunHistoryHistogramNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/{id}/run-history/histogram][%d] getAssetsIdRunHistoryHistogramNotFound %s", 404, payload)
}

func (o *GetAssetsIDRunHistoryHistogramNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetsIDRunHistoryHistogramNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssetsIDRunHistoryHistogramInternalServerError creates a GetAssetsIDRunHistoryHistogramInternalServerError with default headers values
func NewGetAssetsIDRunHistoryHistogramInternalServerError() *GetAssetsIDRunHistoryHistogramInternalServerError {
	return &GetAssetsIDRunHistoryHistogramInternalServerError{}
}

/*
GetAssetsIDRunHistoryHistogramInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAssetsIDRunHistoryHistogramInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get assets Id run history histogram internal server error response has a 2xx status code
func (o *GetAssetsIDRunHistoryHistogramInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get assets Id run history histogram internal server error response has a 3xx status code
func (o *GetAssetsIDRunHistoryHistogramInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets Id run history histogram internal server error response has a 4xx status code
func (o *GetAssetsIDRunHistoryHistogramInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get assets Id run history histogram internal server error response has a 5xx status code
func (o *GetAssetsIDRunHistoryHistogramInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get assets Id run history histogram internal server error response a status code equal to that given
func (o *GetAssetsIDRunHistoryHistogramInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get assets Id run history histogram internal server error response
func (o *GetAssetsIDRunHistoryHistogramInternalServerError) Code() int {
	return 500
}

func (o *GetAssetsIDRunHistoryHistogramInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/{id}/run-history/histogram][%d] getAssetsIdRunHistoryHistogramInternalServerError %s", 500, payload)
}

func (o *GetAssetsIDRunHistoryHistogramInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /assets/{id}/run-history/histogram][%d] getAssetsIdRunHistoryHistogramInternalServerError %s", 500, payload)
}

func (o *GetAssetsIDRunHistoryHistogramInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetsIDRunHistoryHistogramInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
