// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAssetsQualifiedNameQualifiedNameParams creates a new GetAssetsQualifiedNameQualifiedNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetsQualifiedNameQualifiedNameParams() *GetAssetsQualifiedNameQualifiedNameParams {
	return &GetAssetsQualifiedNameQualifiedNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetsQualifiedNameQualifiedNameParamsWithTimeout creates a new GetAssetsQualifiedNameQualifiedNameParams object
// with the ability to set a timeout on a request.
func NewGetAssetsQualifiedNameQualifiedNameParamsWithTimeout(timeout time.Duration) *GetAssetsQualifiedNameQualifiedNameParams {
	return &GetAssetsQualifiedNameQualifiedNameParams{
		timeout: timeout,
	}
}

// NewGetAssetsQualifiedNameQualifiedNameParamsWithContext creates a new GetAssetsQualifiedNameQualifiedNameParams object
// with the ability to set a context for a request.
func NewGetAssetsQualifiedNameQualifiedNameParamsWithContext(ctx context.Context) *GetAssetsQualifiedNameQualifiedNameParams {
	return &GetAssetsQualifiedNameQualifiedNameParams{
		Context: ctx,
	}
}

// NewGetAssetsQualifiedNameQualifiedNameParamsWithHTTPClient creates a new GetAssetsQualifiedNameQualifiedNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetsQualifiedNameQualifiedNameParamsWithHTTPClient(client *http.Client) *GetAssetsQualifiedNameQualifiedNameParams {
	return &GetAssetsQualifiedNameQualifiedNameParams{
		HTTPClient: client,
	}
}

/*
GetAssetsQualifiedNameQualifiedNameParams contains all the parameters to send to the API endpoint

	for the get assets qualified name qualified name operation.

	Typically these are written to a http.Request.
*/
type GetAssetsQualifiedNameQualifiedNameParams struct {

	/* QualifiedName.

	   Asset qualified name
	*/
	QualifiedName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get assets qualified name qualified name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsQualifiedNameQualifiedNameParams) WithDefaults() *GetAssetsQualifiedNameQualifiedNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get assets qualified name qualified name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsQualifiedNameQualifiedNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get assets qualified name qualified name params
func (o *GetAssetsQualifiedNameQualifiedNameParams) WithTimeout(timeout time.Duration) *GetAssetsQualifiedNameQualifiedNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get assets qualified name qualified name params
func (o *GetAssetsQualifiedNameQualifiedNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get assets qualified name qualified name params
func (o *GetAssetsQualifiedNameQualifiedNameParams) WithContext(ctx context.Context) *GetAssetsQualifiedNameQualifiedNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get assets qualified name qualified name params
func (o *GetAssetsQualifiedNameQualifiedNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get assets qualified name qualified name params
func (o *GetAssetsQualifiedNameQualifiedNameParams) WithHTTPClient(client *http.Client) *GetAssetsQualifiedNameQualifiedNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get assets qualified name qualified name params
func (o *GetAssetsQualifiedNameQualifiedNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQualifiedName adds the qualifiedName to the get assets qualified name qualified name params
func (o *GetAssetsQualifiedNameQualifiedNameParams) WithQualifiedName(qualifiedName string) *GetAssetsQualifiedNameQualifiedNameParams {
	o.SetQualifiedName(qualifiedName)
	return o
}

// SetQualifiedName adds the qualifiedName to the get assets qualified name qualified name params
func (o *GetAssetsQualifiedNameQualifiedNameParams) SetQualifiedName(qualifiedName string) {
	o.QualifiedName = qualifiedName
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetsQualifiedNameQualifiedNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param qualifiedName
	if err := r.SetPathParam("qualifiedName", o.QualifiedName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
