// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAssetsIDRunHistoryParams creates a new GetAssetsIDRunHistoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetsIDRunHistoryParams() *GetAssetsIDRunHistoryParams {
	return &GetAssetsIDRunHistoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetsIDRunHistoryParamsWithTimeout creates a new GetAssetsIDRunHistoryParams object
// with the ability to set a timeout on a request.
func NewGetAssetsIDRunHistoryParamsWithTimeout(timeout time.Duration) *GetAssetsIDRunHistoryParams {
	return &GetAssetsIDRunHistoryParams{
		timeout: timeout,
	}
}

// NewGetAssetsIDRunHistoryParamsWithContext creates a new GetAssetsIDRunHistoryParams object
// with the ability to set a context for a request.
func NewGetAssetsIDRunHistoryParamsWithContext(ctx context.Context) *GetAssetsIDRunHistoryParams {
	return &GetAssetsIDRunHistoryParams{
		Context: ctx,
	}
}

// NewGetAssetsIDRunHistoryParamsWithHTTPClient creates a new GetAssetsIDRunHistoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetsIDRunHistoryParamsWithHTTPClient(client *http.Client) *GetAssetsIDRunHistoryParams {
	return &GetAssetsIDRunHistoryParams{
		HTTPClient: client,
	}
}

/*
GetAssetsIDRunHistoryParams contains all the parameters to send to the API endpoint

	for the get assets ID run history operation.

	Typically these are written to a http.Request.
*/
type GetAssetsIDRunHistoryParams struct {

	/* ID.

	   Asset ID
	*/
	ID string

	/* Limit.

	   Number of items per page

	   Default: 10
	*/
	Limit *int64

	/* Offset.

	   Number of items to skip
	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get assets ID run history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsIDRunHistoryParams) WithDefaults() *GetAssetsIDRunHistoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get assets ID run history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsIDRunHistoryParams) SetDefaults() {
	var (
		limitDefault = int64(10)

		offsetDefault = int64(0)
	)

	val := GetAssetsIDRunHistoryParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) WithTimeout(timeout time.Duration) *GetAssetsIDRunHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) WithContext(ctx context.Context) *GetAssetsIDRunHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) WithHTTPClient(client *http.Client) *GetAssetsIDRunHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) WithID(id string) *GetAssetsIDRunHistoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) SetID(id string) {
	o.ID = id
}

// WithLimit adds the limit to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) WithLimit(limit *int64) *GetAssetsIDRunHistoryParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) WithOffset(offset *int64) *GetAssetsIDRunHistoryParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get assets ID run history params
func (o *GetAssetsIDRunHistoryParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetsIDRunHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
