// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// PostAssetsDocumentationReader is a Reader for the PostAssetsDocumentation structure.
type PostAssetsDocumentationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAssetsDocumentationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAssetsDocumentationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAssetsDocumentationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAssetsDocumentationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /assets/documentation] PostAssetsDocumentation", response, response.Code())
	}
}

// NewPostAssetsDocumentationOK creates a PostAssetsDocumentationOK with default headers values
func NewPostAssetsDocumentationOK() *PostAssetsDocumentationOK {
	return &PostAssetsDocumentationOK{}
}

/*
PostAssetsDocumentationOK describes a response with status code 200, with default header values.

OK
*/
type PostAssetsDocumentationOK struct {
	Payload *models.AssetdocsDocumentation
}

// IsSuccess returns true when this post assets documentation o k response has a 2xx status code
func (o *PostAssetsDocumentationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post assets documentation o k response has a 3xx status code
func (o *PostAssetsDocumentationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post assets documentation o k response has a 4xx status code
func (o *PostAssetsDocumentationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post assets documentation o k response has a 5xx status code
func (o *PostAssetsDocumentationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post assets documentation o k response a status code equal to that given
func (o *PostAssetsDocumentationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post assets documentation o k response
func (o *PostAssetsDocumentationOK) Code() int {
	return 200
}

func (o *PostAssetsDocumentationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /assets/documentation][%d] postAssetsDocumentationOK %s", 200, payload)
}

func (o *PostAssetsDocumentationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /assets/documentation][%d] postAssetsDocumentationOK %s", 200, payload)
}

func (o *PostAssetsDocumentationOK) GetPayload() *models.AssetdocsDocumentation {
	return o.Payload
}

func (o *PostAssetsDocumentationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssetdocsDocumentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAssetsDocumentationBadRequest creates a PostAssetsDocumentationBadRequest with default headers values
func NewPostAssetsDocumentationBadRequest() *PostAssetsDocumentationBadRequest {
	return &PostAssetsDocumentationBadRequest{}
}

/*
PostAssetsDocumentationBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAssetsDocumentationBadRequest struct {
	Payload *models.CommonErrorResponse
}

// IsSuccess returns true when this post assets documentation bad request response has a 2xx status code
func (o *PostAssetsDocumentationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post assets documentation bad request response has a 3xx status code
func (o *PostAssetsDocumentationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post assets documentation bad request response has a 4xx status code
func (o *PostAssetsDocumentationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post assets documentation bad request response has a 5xx status code
func (o *PostAssetsDocumentationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post assets documentation bad request response a status code equal to that given
func (o *PostAssetsDocumentationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post assets documentation bad request response
func (o *PostAssetsDocumentationBadRequest) Code() int {
	return 400
}

func (o *PostAssetsDocumentationBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /assets/documentation][%d] postAssetsDocumentationBadRequest %s", 400, payload)
}

func (o *PostAssetsDocumentationBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /assets/documentation][%d] postAssetsDocumentationBadRequest %s", 400, payload)
}

func (o *PostAssetsDocumentationBadRequest) GetPayload() *models.CommonErrorResponse {
	return o.Payload
}

func (o *PostAssetsDocumentationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAssetsDocumentationInternalServerError creates a PostAssetsDocumentationInternalServerError with default headers values
func NewPostAssetsDocumentationInternalServerError() *PostAssetsDocumentationInternalServerError {
	return &PostAssetsDocumentationInternalServerError{}
}

/*
PostAssetsDocumentationInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAssetsDocumentationInternalServerError struct {
	Payload *models.CommonErrorResponse
}

// IsSuccess returns true when this post assets documentation internal server error response has a 2xx status code
func (o *PostAssetsDocumentationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post assets documentation internal server error response has a 3xx status code
func (o *PostAssetsDocumentationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post assets documentation internal server error response has a 4xx status code
func (o *PostAssetsDocumentationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post assets documentation internal server error response has a 5xx status code
func (o *PostAssetsDocumentationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post assets documentation internal server error response a status code equal to that given
func (o *PostAssetsDocumentationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post assets documentation internal server error response
func (o *PostAssetsDocumentationInternalServerError) Code() int {
	return 500
}

func (o *PostAssetsDocumentationInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /assets/documentation][%d] postAssetsDocumentationInternalServerError %s", 500, payload)
}

func (o *PostAssetsDocumentationInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /assets/documentation][%d] postAssetsDocumentationInternalServerError %s", 500, payload)
}

func (o *PostAssetsDocumentationInternalServerError) GetPayload() *models.CommonErrorResponse {
	return o.Payload
}

func (o *PostAssetsDocumentationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
