// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// PutAssetsIDReader is a Reader for the PutAssetsID structure.
type PutAssetsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAssetsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAssetsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAssetsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAssetsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutAssetsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /assets/{id}] PutAssetsID", response, response.Code())
	}
}

// NewPutAssetsIDOK creates a PutAssetsIDOK with default headers values
func NewPutAssetsIDOK() *PutAssetsIDOK {
	return &PutAssetsIDOK{}
}

/*
PutAssetsIDOK describes a response with status code 200, with default header values.

OK
*/
type PutAssetsIDOK struct {
	Payload *models.AssetAsset
}

// IsSuccess returns true when this put assets Id o k response has a 2xx status code
func (o *PutAssetsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put assets Id o k response has a 3xx status code
func (o *PutAssetsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put assets Id o k response has a 4xx status code
func (o *PutAssetsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put assets Id o k response has a 5xx status code
func (o *PutAssetsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put assets Id o k response a status code equal to that given
func (o *PutAssetsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put assets Id o k response
func (o *PutAssetsIDOK) Code() int {
	return 200
}

func (o *PutAssetsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /assets/{id}][%d] putAssetsIdOK %s", 200, payload)
}

func (o *PutAssetsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /assets/{id}][%d] putAssetsIdOK %s", 200, payload)
}

func (o *PutAssetsIDOK) GetPayload() *models.AssetAsset {
	return o.Payload
}

func (o *PutAssetsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssetAsset)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAssetsIDBadRequest creates a PutAssetsIDBadRequest with default headers values
func NewPutAssetsIDBadRequest() *PutAssetsIDBadRequest {
	return &PutAssetsIDBadRequest{}
}

/*
PutAssetsIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutAssetsIDBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put assets Id bad request response has a 2xx status code
func (o *PutAssetsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put assets Id bad request response has a 3xx status code
func (o *PutAssetsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put assets Id bad request response has a 4xx status code
func (o *PutAssetsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put assets Id bad request response has a 5xx status code
func (o *PutAssetsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put assets Id bad request response a status code equal to that given
func (o *PutAssetsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put assets Id bad request response
func (o *PutAssetsIDBadRequest) Code() int {
	return 400
}

func (o *PutAssetsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /assets/{id}][%d] putAssetsIdBadRequest %s", 400, payload)
}

func (o *PutAssetsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /assets/{id}][%d] putAssetsIdBadRequest %s", 400, payload)
}

func (o *PutAssetsIDBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutAssetsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAssetsIDNotFound creates a PutAssetsIDNotFound with default headers values
func NewPutAssetsIDNotFound() *PutAssetsIDNotFound {
	return &PutAssetsIDNotFound{}
}

/*
PutAssetsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutAssetsIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put assets Id not found response has a 2xx status code
func (o *PutAssetsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put assets Id not found response has a 3xx status code
func (o *PutAssetsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put assets Id not found response has a 4xx status code
func (o *PutAssetsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put assets Id not found response has a 5xx status code
func (o *PutAssetsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put assets Id not found response a status code equal to that given
func (o *PutAssetsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put assets Id not found response
func (o *PutAssetsIDNotFound) Code() int {
	return 404
}

func (o *PutAssetsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /assets/{id}][%d] putAssetsIdNotFound %s", 404, payload)
}

func (o *PutAssetsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /assets/{id}][%d] putAssetsIdNotFound %s", 404, payload)
}

func (o *PutAssetsIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutAssetsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAssetsIDInternalServerError creates a PutAssetsIDInternalServerError with default headers values
func NewPutAssetsIDInternalServerError() *PutAssetsIDInternalServerError {
	return &PutAssetsIDInternalServerError{}
}

/*
PutAssetsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutAssetsIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put assets Id internal server error response has a 2xx status code
func (o *PutAssetsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put assets Id internal server error response has a 3xx status code
func (o *PutAssetsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put assets Id internal server error response has a 4xx status code
func (o *PutAssetsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put assets Id internal server error response has a 5xx status code
func (o *PutAssetsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put assets Id internal server error response a status code equal to that given
func (o *PutAssetsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put assets Id internal server error response
func (o *PutAssetsIDInternalServerError) Code() int {
	return 500
}

func (o *PutAssetsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /assets/{id}][%d] putAssetsIdInternalServerError %s", 500, payload)
}

func (o *PutAssetsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /assets/{id}][%d] putAssetsIdInternalServerError %s", 500, payload)
}

func (o *PutAssetsIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutAssetsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
