// Code generated by go-swagger; DO NOT EDIT.

package glossary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteGlossaryIDParams creates a new DeleteGlossaryIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteGlossaryIDParams() *DeleteGlossaryIDParams {
	return &DeleteGlossaryIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteGlossaryIDParamsWithTimeout creates a new DeleteGlossaryIDParams object
// with the ability to set a timeout on a request.
func NewDeleteGlossaryIDParamsWithTimeout(timeout time.Duration) *DeleteGlossaryIDParams {
	return &DeleteGlossaryIDParams{
		timeout: timeout,
	}
}

// NewDeleteGlossaryIDParamsWithContext creates a new DeleteGlossaryIDParams object
// with the ability to set a context for a request.
func NewDeleteGlossaryIDParamsWithContext(ctx context.Context) *DeleteGlossaryIDParams {
	return &DeleteGlossaryIDParams{
		Context: ctx,
	}
}

// NewDeleteGlossaryIDParamsWithHTTPClient creates a new DeleteGlossaryIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteGlossaryIDParamsWithHTTPClient(client *http.Client) *DeleteGlossaryIDParams {
	return &DeleteGlossaryIDParams{
		HTTPClient: client,
	}
}

/*
DeleteGlossaryIDParams contains all the parameters to send to the API endpoint

	for the delete glossary ID operation.

	Typically these are written to a http.Request.
*/
type DeleteGlossaryIDParams struct {

	/* ID.

	   Glossary Term ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete glossary ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteGlossaryIDParams) WithDefaults() *DeleteGlossaryIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete glossary ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteGlossaryIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete glossary ID params
func (o *DeleteGlossaryIDParams) WithTimeout(timeout time.Duration) *DeleteGlossaryIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete glossary ID params
func (o *DeleteGlossaryIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete glossary ID params
func (o *DeleteGlossaryIDParams) WithContext(ctx context.Context) *DeleteGlossaryIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete glossary ID params
func (o *DeleteGlossaryIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete glossary ID params
func (o *DeleteGlossaryIDParams) WithHTTPClient(client *http.Client) *DeleteGlossaryIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete glossary ID params
func (o *DeleteGlossaryIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete glossary ID params
func (o *DeleteGlossaryIDParams) WithID(id string) *DeleteGlossaryIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete glossary ID params
func (o *DeleteGlossaryIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteGlossaryIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
