// Code generated by go-swagger; DO NOT EDIT.

package glossary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// GetGlossaryChildrenIDReader is a Reader for the GetGlossaryChildrenID structure.
type GetGlossaryChildrenIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGlossaryChildrenIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGlossaryChildrenIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGlossaryChildrenIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGlossaryChildrenIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGlossaryChildrenIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /glossary/children/{id}] GetGlossaryChildrenID", response, response.Code())
	}
}

// NewGetGlossaryChildrenIDOK creates a GetGlossaryChildrenIDOK with default headers values
func NewGetGlossaryChildrenIDOK() *GetGlossaryChildrenIDOK {
	return &GetGlossaryChildrenIDOK{}
}

/*
GetGlossaryChildrenIDOK describes a response with status code 200, with default header values.

OK
*/
type GetGlossaryChildrenIDOK struct {
	Payload interface{}
}

// IsSuccess returns true when this get glossary children Id o k response has a 2xx status code
func (o *GetGlossaryChildrenIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get glossary children Id o k response has a 3xx status code
func (o *GetGlossaryChildrenIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get glossary children Id o k response has a 4xx status code
func (o *GetGlossaryChildrenIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get glossary children Id o k response has a 5xx status code
func (o *GetGlossaryChildrenIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get glossary children Id o k response a status code equal to that given
func (o *GetGlossaryChildrenIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get glossary children Id o k response
func (o *GetGlossaryChildrenIDOK) Code() int {
	return 200
}

func (o *GetGlossaryChildrenIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /glossary/children/{id}][%d] getGlossaryChildrenIdOK %s", 200, payload)
}

func (o *GetGlossaryChildrenIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /glossary/children/{id}][%d] getGlossaryChildrenIdOK %s", 200, payload)
}

func (o *GetGlossaryChildrenIDOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetGlossaryChildrenIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGlossaryChildrenIDBadRequest creates a GetGlossaryChildrenIDBadRequest with default headers values
func NewGetGlossaryChildrenIDBadRequest() *GetGlossaryChildrenIDBadRequest {
	return &GetGlossaryChildrenIDBadRequest{}
}

/*
GetGlossaryChildrenIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetGlossaryChildrenIDBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get glossary children Id bad request response has a 2xx status code
func (o *GetGlossaryChildrenIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get glossary children Id bad request response has a 3xx status code
func (o *GetGlossaryChildrenIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get glossary children Id bad request response has a 4xx status code
func (o *GetGlossaryChildrenIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get glossary children Id bad request response has a 5xx status code
func (o *GetGlossaryChildrenIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get glossary children Id bad request response a status code equal to that given
func (o *GetGlossaryChildrenIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get glossary children Id bad request response
func (o *GetGlossaryChildrenIDBadRequest) Code() int {
	return 400
}

func (o *GetGlossaryChildrenIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /glossary/children/{id}][%d] getGlossaryChildrenIdBadRequest %s", 400, payload)
}

func (o *GetGlossaryChildrenIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /glossary/children/{id}][%d] getGlossaryChildrenIdBadRequest %s", 400, payload)
}

func (o *GetGlossaryChildrenIDBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetGlossaryChildrenIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGlossaryChildrenIDNotFound creates a GetGlossaryChildrenIDNotFound with default headers values
func NewGetGlossaryChildrenIDNotFound() *GetGlossaryChildrenIDNotFound {
	return &GetGlossaryChildrenIDNotFound{}
}

/*
GetGlossaryChildrenIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetGlossaryChildrenIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get glossary children Id not found response has a 2xx status code
func (o *GetGlossaryChildrenIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get glossary children Id not found response has a 3xx status code
func (o *GetGlossaryChildrenIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get glossary children Id not found response has a 4xx status code
func (o *GetGlossaryChildrenIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get glossary children Id not found response has a 5xx status code
func (o *GetGlossaryChildrenIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get glossary children Id not found response a status code equal to that given
func (o *GetGlossaryChildrenIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get glossary children Id not found response
func (o *GetGlossaryChildrenIDNotFound) Code() int {
	return 404
}

func (o *GetGlossaryChildrenIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /glossary/children/{id}][%d] getGlossaryChildrenIdNotFound %s", 404, payload)
}

func (o *GetGlossaryChildrenIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /glossary/children/{id}][%d] getGlossaryChildrenIdNotFound %s", 404, payload)
}

func (o *GetGlossaryChildrenIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetGlossaryChildrenIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGlossaryChildrenIDInternalServerError creates a GetGlossaryChildrenIDInternalServerError with default headers values
func NewGetGlossaryChildrenIDInternalServerError() *GetGlossaryChildrenIDInternalServerError {
	return &GetGlossaryChildrenIDInternalServerError{}
}

/*
GetGlossaryChildrenIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetGlossaryChildrenIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get glossary children Id internal server error response has a 2xx status code
func (o *GetGlossaryChildrenIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get glossary children Id internal server error response has a 3xx status code
func (o *GetGlossaryChildrenIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get glossary children Id internal server error response has a 4xx status code
func (o *GetGlossaryChildrenIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get glossary children Id internal server error response has a 5xx status code
func (o *GetGlossaryChildrenIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get glossary children Id internal server error response a status code equal to that given
func (o *GetGlossaryChildrenIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get glossary children Id internal server error response
func (o *GetGlossaryChildrenIDInternalServerError) Code() int {
	return 500
}

func (o *GetGlossaryChildrenIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /glossary/children/{id}][%d] getGlossaryChildrenIdInternalServerError %s", 500, payload)
}

func (o *GetGlossaryChildrenIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /glossary/children/{id}][%d] getGlossaryChildrenIdInternalServerError %s", 500, payload)
}

func (o *GetGlossaryChildrenIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetGlossaryChildrenIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
