// Code generated by go-swagger; DO NOT EDIT.

package glossary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGlossaryAncestorsIDParams creates a new GetGlossaryAncestorsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGlossaryAncestorsIDParams() *GetGlossaryAncestorsIDParams {
	return &GetGlossaryAncestorsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGlossaryAncestorsIDParamsWithTimeout creates a new GetGlossaryAncestorsIDParams object
// with the ability to set a timeout on a request.
func NewGetGlossaryAncestorsIDParamsWithTimeout(timeout time.Duration) *GetGlossaryAncestorsIDParams {
	return &GetGlossaryAncestorsIDParams{
		timeout: timeout,
	}
}

// NewGetGlossaryAncestorsIDParamsWithContext creates a new GetGlossaryAncestorsIDParams object
// with the ability to set a context for a request.
func NewGetGlossaryAncestorsIDParamsWithContext(ctx context.Context) *GetGlossaryAncestorsIDParams {
	return &GetGlossaryAncestorsIDParams{
		Context: ctx,
	}
}

// NewGetGlossaryAncestorsIDParamsWithHTTPClient creates a new GetGlossaryAncestorsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGlossaryAncestorsIDParamsWithHTTPClient(client *http.Client) *GetGlossaryAncestorsIDParams {
	return &GetGlossaryAncestorsIDParams{
		HTTPClient: client,
	}
}

/*
GetGlossaryAncestorsIDParams contains all the parameters to send to the API endpoint

	for the get glossary ancestors ID operation.

	Typically these are written to a http.Request.
*/
type GetGlossaryAncestorsIDParams struct {

	/* ID.

	   Term ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get glossary ancestors ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGlossaryAncestorsIDParams) WithDefaults() *GetGlossaryAncestorsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get glossary ancestors ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGlossaryAncestorsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get glossary ancestors ID params
func (o *GetGlossaryAncestorsIDParams) WithTimeout(timeout time.Duration) *GetGlossaryAncestorsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get glossary ancestors ID params
func (o *GetGlossaryAncestorsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get glossary ancestors ID params
func (o *GetGlossaryAncestorsIDParams) WithContext(ctx context.Context) *GetGlossaryAncestorsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get glossary ancestors ID params
func (o *GetGlossaryAncestorsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get glossary ancestors ID params
func (o *GetGlossaryAncestorsIDParams) WithHTTPClient(client *http.Client) *GetGlossaryAncestorsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get glossary ancestors ID params
func (o *GetGlossaryAncestorsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get glossary ancestors ID params
func (o *GetGlossaryAncestorsIDParams) WithID(id string) *GetGlossaryAncestorsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get glossary ancestors ID params
func (o *GetGlossaryAncestorsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetGlossaryAncestorsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
