// Code generated by go-swagger; DO NOT EDIT.

package lineage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// NewPostAPIV1LineageParams creates a new PostAPIV1LineageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1LineageParams() *PostAPIV1LineageParams {
	return &PostAPIV1LineageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1LineageParamsWithTimeout creates a new PostAPIV1LineageParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1LineageParamsWithTimeout(timeout time.Duration) *PostAPIV1LineageParams {
	return &PostAPIV1LineageParams{
		timeout: timeout,
	}
}

// NewPostAPIV1LineageParamsWithContext creates a new PostAPIV1LineageParams object
// with the ability to set a context for a request.
func NewPostAPIV1LineageParamsWithContext(ctx context.Context) *PostAPIV1LineageParams {
	return &PostAPIV1LineageParams{
		Context: ctx,
	}
}

// NewPostAPIV1LineageParamsWithHTTPClient creates a new PostAPIV1LineageParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1LineageParamsWithHTTPClient(client *http.Client) *PostAPIV1LineageParams {
	return &PostAPIV1LineageParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1LineageParams contains all the parameters to send to the API endpoint

	for the post API v1 lineage operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1LineageParams struct {

	/* Event.

	   OpenLineage run event
	*/
	Event *models.LineageRunEvent

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 lineage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1LineageParams) WithDefaults() *PostAPIV1LineageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 lineage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1LineageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 lineage params
func (o *PostAPIV1LineageParams) WithTimeout(timeout time.Duration) *PostAPIV1LineageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 lineage params
func (o *PostAPIV1LineageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 lineage params
func (o *PostAPIV1LineageParams) WithContext(ctx context.Context) *PostAPIV1LineageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 lineage params
func (o *PostAPIV1LineageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 lineage params
func (o *PostAPIV1LineageParams) WithHTTPClient(client *http.Client) *PostAPIV1LineageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 lineage params
func (o *PostAPIV1LineageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEvent adds the event to the post API v1 lineage params
func (o *PostAPIV1LineageParams) WithEvent(event *models.LineageRunEvent) *PostAPIV1LineageParams {
	o.SetEvent(event)
	return o
}

// SetEvent adds the event to the post API v1 lineage params
func (o *PostAPIV1LineageParams) SetEvent(event *models.LineageRunEvent) {
	o.Event = event
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1LineageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Event != nil {
		if err := r.SetBodyParam(o.Event); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
