// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AssetAssetSource asset asset source
//
// swagger:model asset.AssetSource
type AssetAssetSource struct {

	// last sync at
	LastSyncAt string `json:"last_sync_at,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// priority
	Priority int64 `json:"priority,omitempty"`

	// properties
	Properties interface{} `json:"properties,omitempty"`
}

// Validate validates this asset asset source
func (m *AssetAssetSource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this asset asset source based on context it is used
func (m *AssetAssetSource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AssetAssetSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssetAssetSource) UnmarshalBinary(b []byte) error {
	var res AssetAssetSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
