// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AssetsBatchDocumentationRequest assets batch documentation request
//
// swagger:model assets.BatchDocumentationRequest
type AssetsBatchDocumentationRequest struct {

	// documentation
	// Required: true
	// Min Items: 1
	Documentation []*AssetdocsDocumentation `json:"documentation"`
}

// Validate validates this assets batch documentation request
func (m *AssetsBatchDocumentationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDocumentation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AssetsBatchDocumentationRequest) validateDocumentation(formats strfmt.Registry) error {

	if err := validate.Required("documentation", "body", m.Documentation); err != nil {
		return err
	}

	iDocumentationSize := int64(len(m.Documentation))

	if err := validate.MinItems("documentation", "body", iDocumentationSize, 1); err != nil {
		return err
	}

	for i := 0; i < len(m.Documentation); i++ {
		if swag.IsZero(m.Documentation[i]) { // not required
			continue
		}

		if m.Documentation[i] != nil {
			if err := m.Documentation[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("documentation" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("documentation" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this assets batch documentation request based on the context it is used
func (m *AssetsBatchDocumentationRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDocumentation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AssetsBatchDocumentationRequest) contextValidateDocumentation(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Documentation); i++ {

		if m.Documentation[i] != nil {

			if swag.IsZero(m.Documentation[i]) { // not required
				return nil
			}

			if err := m.Documentation[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("documentation" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("documentation" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AssetsBatchDocumentationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssetsBatchDocumentationRequest) UnmarshalBinary(b []byte) error {
	var res AssetsBatchDocumentationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
