// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComMarmotdataMarmotInternalAPIV1CommonValidationError github com marmotdata marmot internal api v1 common validation error
//
// swagger:model github_com_marmotdata_marmot_internal_api_v1_common.ValidationError
type GithubComMarmotdataMarmotInternalAPIV1CommonValidationError struct {

	// field
	Field string `json:"field,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this github com marmotdata marmot internal api v1 common validation error
func (m *GithubComMarmotdataMarmotInternalAPIV1CommonValidationError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com marmotdata marmot internal api v1 common validation error based on context it is used
func (m *GithubComMarmotdataMarmotInternalAPIV1CommonValidationError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComMarmotdataMarmotInternalAPIV1CommonValidationError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComMarmotdataMarmotInternalAPIV1CommonValidationError) UnmarshalBinary(b []byte) error {
	var res GithubComMarmotdataMarmotInternalAPIV1CommonValidationError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
