// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricsAssetCount metrics asset count
//
// swagger:model metrics.AssetCount
type MetricsAssetCount struct {

	// asset id
	AssetID string `json:"asset_id,omitempty"`

	// asset name
	AssetName string `json:"asset_name,omitempty"`

	// asset provider
	AssetProvider string `json:"asset_provider,omitempty"`

	// asset type
	AssetType string `json:"asset_type,omitempty"`

	// count
	Count int64 `json:"count,omitempty"`
}

// Validate validates this metrics asset count
func (m *MetricsAssetCount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metrics asset count based on context it is used
func (m *MetricsAssetCount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricsAssetCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricsAssetCount) UnmarshalBinary(b []byte) error {
	var res MetricsAssetCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
