// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SearchFacetValue search facet value
//
// swagger:model search.FacetValue
type SearchFacetValue struct {

	// count
	Count int64 `json:"count,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this search facet value
func (m *SearchFacetValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this search facet value based on context it is used
func (m *SearchFacetValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SearchFacetValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchFacetValue) UnmarshalBinary(b []byte) error {
	var res SearchFacetValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
