// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AssetsAssetSummaryResponse v1 assets asset summary response
//
// swagger:model v1_assets.AssetSummaryResponse
type V1AssetsAssetSummaryResponse struct {

	// services
	Services map[string]int64 `json:"services,omitempty"`

	// tags
	Tags map[string]int64 `json:"tags,omitempty"`

	// types
	Types map[string]int64 `json:"types,omitempty"`
}

// Validate validates this v1 assets asset summary response
func (m *V1AssetsAssetSummaryResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 assets asset summary response based on context it is used
func (m *V1AssetsAssetSummaryResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AssetsAssetSummaryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AssetsAssetSummaryResponse) UnmarshalBinary(b []byte) error {
	var res V1AssetsAssetSummaryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
