// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1AssetsDocumentationCreateRequest v1 assets documentation create request
//
// swagger:model v1_assets.DocumentationCreateRequest
type V1AssetsDocumentationCreateRequest struct {

	// content
	// Required: true
	Content *string `json:"content"`

	// mrn
	// Required: true
	Mrn *string `json:"mrn"`

	// source
	// Required: true
	Source *string `json:"source"`
}

// Validate validates this v1 assets documentation create request
func (m *V1AssetsDocumentationCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMrn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1AssetsDocumentationCreateRequest) validateContent(formats strfmt.Registry) error {

	if err := validate.Required("content", "body", m.Content); err != nil {
		return err
	}

	return nil
}

func (m *V1AssetsDocumentationCreateRequest) validateMrn(formats strfmt.Registry) error {

	if err := validate.Required("mrn", "body", m.Mrn); err != nil {
		return err
	}

	return nil
}

func (m *V1AssetsDocumentationCreateRequest) validateSource(formats strfmt.Registry) error {

	if err := validate.Required("source", "body", m.Source); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 assets documentation create request based on context it is used
func (m *V1AssetsDocumentationCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AssetsDocumentationCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AssetsDocumentationCreateRequest) UnmarshalBinary(b []byte) error {
	var res V1AssetsDocumentationCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
