// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1GlossaryOwnerRequest v1 glossary owner request
//
// swagger:model v1_glossary.OwnerRequest
type V1GlossaryOwnerRequest struct {

	// id
	// Required: true
	ID *string `json:"id"`

	// type
	// Required: true
	// Enum: ["user","team"]
	Type *string `json:"type"`
}

// Validate validates this v1 glossary owner request
func (m *V1GlossaryOwnerRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1GlossaryOwnerRequest) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

var v1GlossaryOwnerRequestTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["user","team"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1GlossaryOwnerRequestTypeTypePropEnum = append(v1GlossaryOwnerRequestTypeTypePropEnum, v)
	}
}

const (

	// V1GlossaryOwnerRequestTypeUser captures enum value "user"
	V1GlossaryOwnerRequestTypeUser string = "user"

	// V1GlossaryOwnerRequestTypeTeam captures enum value "team"
	V1GlossaryOwnerRequestTypeTeam string = "team"
)

// prop value enum
func (m *V1GlossaryOwnerRequest) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, v1GlossaryOwnerRequestTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *V1GlossaryOwnerRequest) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 glossary owner request based on context it is used
func (m *V1GlossaryOwnerRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1GlossaryOwnerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GlossaryOwnerRequest) UnmarshalBinary(b []byte) error {
	var res V1GlossaryOwnerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
