// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1RunsCreateAssetRequest v1 runs create asset request
//
// swagger:model v1_runs.CreateAssetRequest
type V1RunsCreateAssetRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// external links
	ExternalLinks []map[string]string `json:"external_links"`

	// metadata
	Metadata interface{} `json:"metadata,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// providers
	Providers []string `json:"providers"`

	// schema
	Schema interface{} `json:"schema,omitempty"`

	// sources
	Sources []string `json:"sources"`

	// tags
	Tags []string `json:"tags"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this v1 runs create asset request
func (m *V1RunsCreateAssetRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 runs create asset request based on context it is used
func (m *V1RunsCreateAssetRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1RunsCreateAssetRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1RunsCreateAssetRequest) UnmarshalBinary(b []byte) error {
	var res V1RunsCreateAssetRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
