// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1RunsCreateDocRequest v1 runs create doc request
//
// swagger:model v1_runs.CreateDocRequest
type V1RunsCreateDocRequest struct {

	// asset mrn
	AssetMrn string `json:"asset_mrn,omitempty"`

	// content
	Content string `json:"content,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this v1 runs create doc request
func (m *V1RunsCreateDocRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 runs create doc request based on context it is used
func (m *V1RunsCreateDocRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1RunsCreateDocRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1RunsCreateDocRequest) UnmarshalBinary(b []byte) error {
	var res V1RunsCreateDocRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
