// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SchedulesCreateScheduleRequest v1 schedules create schedule request
//
// swagger:model v1_schedules.CreateScheduleRequest
type V1SchedulesCreateScheduleRequest struct {

	// config
	Config interface{} `json:"config,omitempty"`

	// cron expression
	CronExpression string `json:"cron_expression,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// plugin id
	PluginID string `json:"plugin_id,omitempty"`
}

// Validate validates this v1 schedules create schedule request
func (m *V1SchedulesCreateScheduleRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 schedules create schedule request based on context it is used
func (m *V1SchedulesCreateScheduleRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1SchedulesCreateScheduleRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SchedulesCreateScheduleRequest) UnmarshalBinary(b []byte) error {
	var res V1SchedulesCreateScheduleRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
