// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1UIUIConfigResponse v1 ui UI config response
//
// swagger:model v1_ui.UIConfigResponse
type V1UIUIConfigResponse struct {

	// banner
	Banner *V1UIBannerResponse `json:"banner,omitempty"`
}

// Validate validates this v1 ui UI config response
func (m *V1UIUIConfigResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBanner(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1UIUIConfigResponse) validateBanner(formats strfmt.Registry) error {
	if swag.IsZero(m.Banner) { // not required
		return nil
	}

	if m.Banner != nil {
		if err := m.Banner.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("banner")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("banner")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 ui UI config response based on the context it is used
func (m *V1UIUIConfigResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBanner(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1UIUIConfigResponse) contextValidateBanner(ctx context.Context, formats strfmt.Registry) error {

	if m.Banner != nil {

		if swag.IsZero(m.Banner) { // not required
			return nil
		}

		if err := m.Banner.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("banner")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("banner")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1UIUIConfigResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1UIUIConfigResponse) UnmarshalBinary(b []byte) error {
	var res V1UIUIConfigResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
