// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// DeleteUsersIDReader is a Reader for the DeleteUsersID structure.
type DeleteUsersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUsersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteUsersIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteUsersIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteUsersIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /users/{id}] DeleteUsersID", response, response.Code())
	}
}

// NewDeleteUsersIDNoContent creates a DeleteUsersIDNoContent with default headers values
func NewDeleteUsersIDNoContent() *DeleteUsersIDNoContent {
	return &DeleteUsersIDNoContent{}
}

/*
DeleteUsersIDNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteUsersIDNoContent struct {
}

// IsSuccess returns true when this delete users Id no content response has a 2xx status code
func (o *DeleteUsersIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete users Id no content response has a 3xx status code
func (o *DeleteUsersIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete users Id no content response has a 4xx status code
func (o *DeleteUsersIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete users Id no content response has a 5xx status code
func (o *DeleteUsersIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete users Id no content response a status code equal to that given
func (o *DeleteUsersIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete users Id no content response
func (o *DeleteUsersIDNoContent) Code() int {
	return 204
}

func (o *DeleteUsersIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdNoContent", 204)
}

func (o *DeleteUsersIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdNoContent", 204)
}

func (o *DeleteUsersIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUsersIDNotFound creates a DeleteUsersIDNotFound with default headers values
func NewDeleteUsersIDNotFound() *DeleteUsersIDNotFound {
	return &DeleteUsersIDNotFound{}
}

/*
DeleteUsersIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteUsersIDNotFound struct {
	Payload *models.CommonErrorResponse
}

// IsSuccess returns true when this delete users Id not found response has a 2xx status code
func (o *DeleteUsersIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete users Id not found response has a 3xx status code
func (o *DeleteUsersIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete users Id not found response has a 4xx status code
func (o *DeleteUsersIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete users Id not found response has a 5xx status code
func (o *DeleteUsersIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete users Id not found response a status code equal to that given
func (o *DeleteUsersIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete users Id not found response
func (o *DeleteUsersIDNotFound) Code() int {
	return 404
}

func (o *DeleteUsersIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdNotFound %s", 404, payload)
}

func (o *DeleteUsersIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdNotFound %s", 404, payload)
}

func (o *DeleteUsersIDNotFound) GetPayload() *models.CommonErrorResponse {
	return o.Payload
}

func (o *DeleteUsersIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersIDInternalServerError creates a DeleteUsersIDInternalServerError with default headers values
func NewDeleteUsersIDInternalServerError() *DeleteUsersIDInternalServerError {
	return &DeleteUsersIDInternalServerError{}
}

/*
DeleteUsersIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteUsersIDInternalServerError struct {
	Payload *models.CommonErrorResponse
}

// IsSuccess returns true when this delete users Id internal server error response has a 2xx status code
func (o *DeleteUsersIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete users Id internal server error response has a 3xx status code
func (o *DeleteUsersIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete users Id internal server error response has a 4xx status code
func (o *DeleteUsersIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete users Id internal server error response has a 5xx status code
func (o *DeleteUsersIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete users Id internal server error response a status code equal to that given
func (o *DeleteUsersIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete users Id internal server error response
func (o *DeleteUsersIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteUsersIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdInternalServerError %s", 500, payload)
}

func (o *DeleteUsersIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdInternalServerError %s", 500, payload)
}

func (o *DeleteUsersIDInternalServerError) GetPayload() *models.CommonErrorResponse {
	return o.Payload
}

func (o *DeleteUsersIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
