// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// NewPostUsersLoginParams creates a new PostUsersLoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostUsersLoginParams() *PostUsersLoginParams {
	return &PostUsersLoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostUsersLoginParamsWithTimeout creates a new PostUsersLoginParams object
// with the ability to set a timeout on a request.
func NewPostUsersLoginParamsWithTimeout(timeout time.Duration) *PostUsersLoginParams {
	return &PostUsersLoginParams{
		timeout: timeout,
	}
}

// NewPostUsersLoginParamsWithContext creates a new PostUsersLoginParams object
// with the ability to set a context for a request.
func NewPostUsersLoginParamsWithContext(ctx context.Context) *PostUsersLoginParams {
	return &PostUsersLoginParams{
		Context: ctx,
	}
}

// NewPostUsersLoginParamsWithHTTPClient creates a new PostUsersLoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostUsersLoginParamsWithHTTPClient(client *http.Client) *PostUsersLoginParams {
	return &PostUsersLoginParams{
		HTTPClient: client,
	}
}

/*
PostUsersLoginParams contains all the parameters to send to the API endpoint

	for the post users login operation.

	Typically these are written to a http.Request.
*/
type PostUsersLoginParams struct {

	/* Credentials.

	   Login credentials
	*/
	Credentials *models.UsersLoginRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post users login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUsersLoginParams) WithDefaults() *PostUsersLoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post users login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUsersLoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post users login params
func (o *PostUsersLoginParams) WithTimeout(timeout time.Duration) *PostUsersLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post users login params
func (o *PostUsersLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post users login params
func (o *PostUsersLoginParams) WithContext(ctx context.Context) *PostUsersLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post users login params
func (o *PostUsersLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post users login params
func (o *PostUsersLoginParams) WithHTTPClient(client *http.Client) *PostUsersLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post users login params
func (o *PostUsersLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCredentials adds the credentials to the post users login params
func (o *PostUsersLoginParams) WithCredentials(credentials *models.UsersLoginRequest) *PostUsersLoginParams {
	o.SetCredentials(credentials)
	return o
}

// SetCredentials adds the credentials to the post users login params
func (o *PostUsersLoginParams) SetCredentials(credentials *models.UsersLoginRequest) {
	o.Credentials = credentials
}

// WriteToRequest writes these params to a swagger request
func (o *PostUsersLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Credentials != nil {
		if err := r.SetBodyParam(o.Credentials); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
