// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/terraform-provider-marmot/internal/client/models"
)

// NewPostUsersOauthLinkParams creates a new PostUsersOauthLinkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostUsersOauthLinkParams() *PostUsersOauthLinkParams {
	return &PostUsersOauthLinkParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostUsersOauthLinkParamsWithTimeout creates a new PostUsersOauthLinkParams object
// with the ability to set a timeout on a request.
func NewPostUsersOauthLinkParamsWithTimeout(timeout time.Duration) *PostUsersOauthLinkParams {
	return &PostUsersOauthLinkParams{
		timeout: timeout,
	}
}

// NewPostUsersOauthLinkParamsWithContext creates a new PostUsersOauthLinkParams object
// with the ability to set a context for a request.
func NewPostUsersOauthLinkParamsWithContext(ctx context.Context) *PostUsersOauthLinkParams {
	return &PostUsersOauthLinkParams{
		Context: ctx,
	}
}

// NewPostUsersOauthLinkParamsWithHTTPClient creates a new PostUsersOauthLinkParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostUsersOauthLinkParamsWithHTTPClient(client *http.Client) *PostUsersOauthLinkParams {
	return &PostUsersOauthLinkParams{
		HTTPClient: client,
	}
}

/*
PostUsersOauthLinkParams contains all the parameters to send to the API endpoint

	for the post users oauth link operation.

	Typically these are written to a http.Request.
*/
type PostUsersOauthLinkParams struct {

	/* Link.

	   OAuth account link request
	*/
	Link *models.V1UsersOAuthLinkRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post users oauth link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUsersOauthLinkParams) WithDefaults() *PostUsersOauthLinkParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post users oauth link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUsersOauthLinkParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post users oauth link params
func (o *PostUsersOauthLinkParams) WithTimeout(timeout time.Duration) *PostUsersOauthLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post users oauth link params
func (o *PostUsersOauthLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post users oauth link params
func (o *PostUsersOauthLinkParams) WithContext(ctx context.Context) *PostUsersOauthLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post users oauth link params
func (o *PostUsersOauthLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post users oauth link params
func (o *PostUsersOauthLinkParams) WithHTTPClient(client *http.Client) *PostUsersOauthLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post users oauth link params
func (o *PostUsersOauthLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLink adds the link to the post users oauth link params
func (o *PostUsersOauthLinkParams) WithLink(link *models.V1UsersOAuthLinkRequest) *PostUsersOauthLinkParams {
	o.SetLink(link)
	return o
}

// SetLink adds the link to the post users oauth link params
func (o *PostUsersOauthLinkParams) SetLink(link *models.V1UsersOAuthLinkRequest) {
	o.Link = link
}

// WriteToRequest writes these params to a swagger request
func (o *PostUsersOauthLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Link != nil {
		if err := r.SetBodyParam(o.Link); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
