// Code generated by go-swagger; DO NOT EDIT.

package ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUIConfigParams creates a new GetUIConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUIConfigParams() *GetUIConfigParams {
	return &GetUIConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUIConfigParamsWithTimeout creates a new GetUIConfigParams object
// with the ability to set a timeout on a request.
func NewGetUIConfigParamsWithTimeout(timeout time.Duration) *GetUIConfigParams {
	return &GetUIConfigParams{
		timeout: timeout,
	}
}

// NewGetUIConfigParamsWithContext creates a new GetUIConfigParams object
// with the ability to set a context for a request.
func NewGetUIConfigParamsWithContext(ctx context.Context) *GetUIConfigParams {
	return &GetUIConfigParams{
		Context: ctx,
	}
}

// NewGetUIConfigParamsWithHTTPClient creates a new GetUIConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUIConfigParamsWithHTTPClient(client *http.Client) *GetUIConfigParams {
	return &GetUIConfigParams{
		HTTPClient: client,
	}
}

/*
GetUIConfigParams contains all the parameters to send to the API endpoint

	for the get UI config operation.

	Typically these are written to a http.Request.
*/
type GetUIConfigParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get UI config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUIConfigParams) WithDefaults() *GetUIConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get UI config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUIConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get UI config params
func (o *GetUIConfigParams) WithTimeout(timeout time.Duration) *GetUIConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get UI config params
func (o *GetUIConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get UI config params
func (o *GetUIConfigParams) WithContext(ctx context.Context) *GetUIConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get UI config params
func (o *GetUIConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get UI config params
func (o *GetUIConfigParams) WithHTTPClient(client *http.Client) *GetUIConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get UI config params
func (o *GetUIConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetUIConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
